// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: chromatograph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRun_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRun_Parameters) Reset() {
	*x = StartRun_Parameters{}
	mi := &file_chromatograph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRun_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun_Parameters) ProtoMessage() {}

func (x *StartRun_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun_Parameters.ProtoReflect.Descriptor instead.
func (*StartRun_Parameters) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{0}
}

type StartRun_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRun_Responses) Reset() {
	*x = StartRun_Responses{}
	mi := &file_chromatograph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRun_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun_Responses) ProtoMessage() {}

func (x *StartRun_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun_Responses.ProtoReflect.Descriptor instead.
func (*StartRun_Responses) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{1}
}

type StopRun_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRun_Parameters) Reset() {
	*x = StopRun_Parameters{}
	mi := &file_chromatograph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRun_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRun_Parameters) ProtoMessage() {}

func (x *StopRun_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRun_Parameters.ProtoReflect.Descriptor instead.
func (*StopRun_Parameters) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{2}
}

type StopRun_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRun_Responses) Reset() {
	*x = StopRun_Responses{}
	mi := &file_chromatograph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRun_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRun_Responses) ProtoMessage() {}

func (x *StopRun_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRun_Responses.ProtoReflect.Descriptor instead.
func (*StopRun_Responses) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{3}
}

type PauseRun_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRun_Parameters) Reset() {
	*x = PauseRun_Parameters{}
	mi := &file_chromatograph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRun_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRun_Parameters) ProtoMessage() {}

func (x *PauseRun_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRun_Parameters.ProtoReflect.Descriptor instead.
func (*PauseRun_Parameters) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{4}
}

type PauseRun_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRun_Responses) Reset() {
	*x = PauseRun_Responses{}
	mi := &file_chromatograph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRun_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRun_Responses) ProtoMessage() {}

func (x *PauseRun_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRun_Responses.ProtoReflect.Descriptor instead.
func (*PauseRun_Responses) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{5}
}

type ResumeRun_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRun_Parameters) Reset() {
	*x = ResumeRun_Parameters{}
	mi := &file_chromatograph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRun_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRun_Parameters) ProtoMessage() {}

func (x *ResumeRun_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRun_Parameters.ProtoReflect.Descriptor instead.
func (*ResumeRun_Parameters) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{6}
}

type ResumeRun_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRun_Responses) Reset() {
	*x = ResumeRun_Responses{}
	mi := &file_chromatograph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRun_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRun_Responses) ProtoMessage() {}

func (x *ResumeRun_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRun_Responses.ProtoReflect.Descriptor instead.
func (*ResumeRun_Responses) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{7}
}

type AbortRun_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRun_Parameters) Reset() {
	*x = AbortRun_Parameters{}
	mi := &file_chromatograph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRun_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRun_Parameters) ProtoMessage() {}

func (x *AbortRun_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRun_Parameters.ProtoReflect.Descriptor instead.
func (*AbortRun_Parameters) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{8}
}

type AbortRun_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRun_Responses) Reset() {
	*x = AbortRun_Responses{}
	mi := &file_chromatograph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRun_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRun_Responses) ProtoMessage() {}

func (x *AbortRun_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRun_Responses.ProtoReflect.Descriptor instead.
func (*AbortRun_Responses) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{9}
}

type GetState_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetState_Parameters) Reset() {
	*x = GetState_Parameters{}
	mi := &file_chromatograph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetState_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetState_Parameters) ProtoMessage() {}

func (x *GetState_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetState_Parameters.ProtoReflect.Descriptor instead.
func (*GetState_Parameters) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{10}
}

type GetState_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentState  *String                `protobuf:"bytes,1,opt,name=CurrentState,proto3" json:"CurrentState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetState_Responses) Reset() {
	*x = GetState_Responses{}
	mi := &file_chromatograph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetState_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetState_Responses) ProtoMessage() {}

func (x *GetState_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_chromatograph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetState_Responses.ProtoReflect.Descriptor instead.
func (*GetState_Responses) Descriptor() ([]byte, []int) {
	return file_chromatograph_proto_rawDescGZIP(), []int{11}
}

func (x *GetState_Responses) GetCurrentState() *String {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

var File_chromatograph_proto protoreflect.FileDescriptor

const file_chromatograph_proto_rawDesc = "" +
	"\n" +
	"\x13chromatograph.proto\x123sila2.org.silastandard.core.chromatographservice.v1\x1a\x13SiLAFramework.proto\"\x15\n" +
	"\x13StartRun_Parameters\"\x14\n" +
	"\x12StartRun_Responses\"\x14\n" +
	"\x12StopRun_Parameters\"\x13\n" +
	"\x11StopRun_Responses\"\x15\n" +
	"\x13PauseRun_Parameters\"\x14\n" +
	"\x12PauseRun_Responses\"\x16\n" +
	"\x14ResumeRun_Parameters\"\x15\n" +
	"\x13ResumeRun_Responses\"\x15\n" +
	"\x13AbortRun_Parameters\"\x14\n" +
	"\x12AbortRun_Responses\"\x15\n" +
	"\x13GetState_Parameters\"X\n" +
	"\x12GetState_Responses\x12B\n" +
	"\fCurrentState\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\fCurrentState2\xe2\a\n" +
	"\x14ChromatographService\x12\x9f\x01\n" +
	"\bStartRun\x12H.sila2.org.silastandard.core.chromatographservice.v1.StartRun_Parameters\x1aG.sila2.org.silastandard.core.chromatographservice.v1.StartRun_Responses\"\x00\x12\x9c\x01\n" +
	"\aStopRun\x12G.sila2.org.silastandard.core.chromatographservice.v1.StopRun_Parameters\x1aF.sila2.org.silastandard.core.chromatographservice.v1.StopRun_Responses\"\x00\x12\x9f\x01\n" +
	"\bPauseRun\x12H.sila2.org.silastandard.core.chromatographservice.v1.PauseRun_Parameters\x1aG.sila2.org.silastandard.core.chromatographservice.v1.PauseRun_Responses\"\x00\x12\xa2\x01\n" +
	"\tResumeRun\x12I.sila2.org.silastandard.core.chromatographservice.v1.ResumeRun_Parameters\x1aH.sila2.org.silastandard.core.chromatographservice.v1.ResumeRun_Responses\"\x00\x12\x9f\x01\n" +
	"\bAbortRun\x12H.sila2.org.silastandard.core.chromatographservice.v1.AbortRun_Parameters\x1aG.sila2.org.silastandard.core.chromatographservice.v1.AbortRun_Responses\"\x00\x12\x9f\x01\n" +
	"\bGetState\x12H.sila2.org.silastandard.core.chromatographservice.v1.GetState_Parameters\x1aG.sila2.org.silastandard.core.chromatographservice.v1.GetState_Responses\"\x00B6Z4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_chromatograph_proto_rawDescOnce sync.Once
	file_chromatograph_proto_rawDescData []byte
)

func file_chromatograph_proto_rawDescGZIP() []byte {
	file_chromatograph_proto_rawDescOnce.Do(func() {
		file_chromatograph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chromatograph_proto_rawDesc), len(file_chromatograph_proto_rawDesc)))
	})
	return file_chromatograph_proto_rawDescData
}

var file_chromatograph_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chromatograph_proto_goTypes = []any{
	(*StartRun_Parameters)(nil),  // 0: sila2.org.silastandard.core.chromatographservice.v1.StartRun_Parameters
	(*StartRun_Responses)(nil),   // 1: sila2.org.silastandard.core.chromatographservice.v1.StartRun_Responses
	(*StopRun_Parameters)(nil),   // 2: sila2.org.silastandard.core.chromatographservice.v1.StopRun_Parameters
	(*StopRun_Responses)(nil),    // 3: sila2.org.silastandard.core.chromatographservice.v1.StopRun_Responses
	(*PauseRun_Parameters)(nil),  // 4: sila2.org.silastandard.core.chromatographservice.v1.PauseRun_Parameters
	(*PauseRun_Responses)(nil),   // 5: sila2.org.silastandard.core.chromatographservice.v1.PauseRun_Responses
	(*ResumeRun_Parameters)(nil), // 6: sila2.org.silastandard.core.chromatographservice.v1.ResumeRun_Parameters
	(*ResumeRun_Responses)(nil),  // 7: sila2.org.silastandard.core.chromatographservice.v1.ResumeRun_Responses
	(*AbortRun_Parameters)(nil),  // 8: sila2.org.silastandard.core.chromatographservice.v1.AbortRun_Parameters
	(*AbortRun_Responses)(nil),   // 9: sila2.org.silastandard.core.chromatographservice.v1.AbortRun_Responses
	(*GetState_Parameters)(nil),  // 10: sila2.org.silastandard.core.chromatographservice.v1.GetState_Parameters
	(*GetState_Responses)(nil),   // 11: sila2.org.silastandard.core.chromatographservice.v1.GetState_Responses
	(*String)(nil),               // 12: sila2.org.silastandard.String
}
var file_chromatograph_proto_depIdxs = []int32{
	12, // 0: sila2.org.silastandard.core.chromatographservice.v1.GetState_Responses.CurrentState:type_name -> sila2.org.silastandard.String
	0,  // 1: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.StartRun:input_type -> sila2.org.silastandard.core.chromatographservice.v1.StartRun_Parameters
	2,  // 2: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.StopRun:input_type -> sila2.org.silastandard.core.chromatographservice.v1.StopRun_Parameters
	4,  // 3: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.PauseRun:input_type -> sila2.org.silastandard.core.chromatographservice.v1.PauseRun_Parameters
	6,  // 4: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.ResumeRun:input_type -> sila2.org.silastandard.core.chromatographservice.v1.ResumeRun_Parameters
	8,  // 5: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.AbortRun:input_type -> sila2.org.silastandard.core.chromatographservice.v1.AbortRun_Parameters
	10, // 6: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.GetState:input_type -> sila2.org.silastandard.core.chromatographservice.v1.GetState_Parameters
	1,  // 7: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.StartRun:output_type -> sila2.org.silastandard.core.chromatographservice.v1.StartRun_Responses
	3,  // 8: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.StopRun:output_type -> sila2.org.silastandard.core.chromatographservice.v1.StopRun_Responses
	5,  // 9: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.PauseRun:output_type -> sila2.org.silastandard.core.chromatographservice.v1.PauseRun_Responses
	7,  // 10: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.ResumeRun:output_type -> sila2.org.silastandard.core.chromatographservice.v1.ResumeRun_Responses
	9,  // 11: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.AbortRun:output_type -> sila2.org.silastandard.core.chromatographservice.v1.AbortRun_Responses
	11, // 12: sila2.org.silastandard.core.chromatographservice.v1.ChromatographService.GetState:output_type -> sila2.org.silastandard.core.chromatographservice.v1.GetState_Responses
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_chromatograph_proto_init() }
func file_chromatograph_proto_init() {
	if File_chromatograph_proto != nil {
		return
	}
	file_SiLAFramework_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chromatograph_proto_rawDesc), len(file_chromatograph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chromatograph_proto_goTypes,
		DependencyIndexes: file_chromatograph_proto_depIdxs,
		MessageInfos:      file_chromatograph_proto_msgTypes,
	}.Build()
	File_chromatograph_proto = out.File
	file_chromatograph_proto_goTypes = nil
	file_chromatograph_proto_depIdxs = nil
}
