// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: chromatograph.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChromatographService_StartRun_FullMethodName  = "/sila2.org.silastandard.core.chromatographservice.v1.ChromatographService/StartRun"
	ChromatographService_StopRun_FullMethodName   = "/sila2.org.silastandard.core.chromatographservice.v1.ChromatographService/StopRun"
	ChromatographService_PauseRun_FullMethodName  = "/sila2.org.silastandard.core.chromatographservice.v1.ChromatographService/PauseRun"
	ChromatographService_ResumeRun_FullMethodName = "/sila2.org.silastandard.core.chromatographservice.v1.ChromatographService/ResumeRun"
	ChromatographService_AbortRun_FullMethodName  = "/sila2.org.silastandard.core.chromatographservice.v1.ChromatographService/AbortRun"
	ChromatographService_GetState_FullMethodName  = "/sila2.org.silastandard.core.chromatographservice.v1.ChromatographService/GetState"
)

// ChromatographServiceClient is the client API for ChromatographService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The standard SiLA 2 service for a Chromatography device
type ChromatographServiceClient interface {
	// Starts a new chromatography run
	StartRun(ctx context.Context, in *StartRun_Parameters, opts ...grpc.CallOption) (*StartRun_Responses, error)
	// Stops the current run (Graceful stop)
	StopRun(ctx context.Context, in *StopRun_Parameters, opts ...grpc.CallOption) (*StopRun_Responses, error)
	// Pauses the current run
	PauseRun(ctx context.Context, in *PauseRun_Parameters, opts ...grpc.CallOption) (*PauseRun_Responses, error)
	// Resumes a paused run
	ResumeRun(ctx context.Context, in *ResumeRun_Parameters, opts ...grpc.CallOption) (*ResumeRun_Responses, error)
	// Aborts the current run (Emergency stop)
	AbortRun(ctx context.Context, in *AbortRun_Parameters, opts ...grpc.CallOption) (*AbortRun_Responses, error)
	// Gets the current standard state of the digital twin
	GetState(ctx context.Context, in *GetState_Parameters, opts ...grpc.CallOption) (*GetState_Responses, error)
}

type chromatographServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChromatographServiceClient(cc grpc.ClientConnInterface) ChromatographServiceClient {
	return &chromatographServiceClient{cc}
}

func (c *chromatographServiceClient) StartRun(ctx context.Context, in *StartRun_Parameters, opts ...grpc.CallOption) (*StartRun_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRun_Responses)
	err := c.cc.Invoke(ctx, ChromatographService_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) StopRun(ctx context.Context, in *StopRun_Parameters, opts ...grpc.CallOption) (*StopRun_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRun_Responses)
	err := c.cc.Invoke(ctx, ChromatographService_StopRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) PauseRun(ctx context.Context, in *PauseRun_Parameters, opts ...grpc.CallOption) (*PauseRun_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseRun_Responses)
	err := c.cc.Invoke(ctx, ChromatographService_PauseRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) ResumeRun(ctx context.Context, in *ResumeRun_Parameters, opts ...grpc.CallOption) (*ResumeRun_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeRun_Responses)
	err := c.cc.Invoke(ctx, ChromatographService_ResumeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) AbortRun(ctx context.Context, in *AbortRun_Parameters, opts ...grpc.CallOption) (*AbortRun_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortRun_Responses)
	err := c.cc.Invoke(ctx, ChromatographService_AbortRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) GetState(ctx context.Context, in *GetState_Parameters, opts ...grpc.CallOption) (*GetState_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetState_Responses)
	err := c.cc.Invoke(ctx, ChromatographService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChromatographServiceServer is the server API for ChromatographService service.
// All implementations must embed UnimplementedChromatographServiceServer
// for forward compatibility.
//
// The standard SiLA 2 service for a Chromatography device
type ChromatographServiceServer interface {
	// Starts a new chromatography run
	StartRun(context.Context, *StartRun_Parameters) (*StartRun_Responses, error)
	// Stops the current run (Graceful stop)
	StopRun(context.Context, *StopRun_Parameters) (*StopRun_Responses, error)
	// Pauses the current run
	PauseRun(context.Context, *PauseRun_Parameters) (*PauseRun_Responses, error)
	// Resumes a paused run
	ResumeRun(context.Context, *ResumeRun_Parameters) (*ResumeRun_Responses, error)
	// Aborts the current run (Emergency stop)
	AbortRun(context.Context, *AbortRun_Parameters) (*AbortRun_Responses, error)
	// Gets the current standard state of the digital twin
	GetState(context.Context, *GetState_Parameters) (*GetState_Responses, error)
	mustEmbedUnimplementedChromatographServiceServer()
}

// UnimplementedChromatographServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChromatographServiceServer struct{}

func (UnimplementedChromatographServiceServer) StartRun(context.Context, *StartRun_Parameters) (*StartRun_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedChromatographServiceServer) StopRun(context.Context, *StopRun_Parameters) (*StopRun_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRun not implemented")
}
func (UnimplementedChromatographServiceServer) PauseRun(context.Context, *PauseRun_Parameters) (*PauseRun_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseRun not implemented")
}
func (UnimplementedChromatographServiceServer) ResumeRun(context.Context, *ResumeRun_Parameters) (*ResumeRun_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRun not implemented")
}
func (UnimplementedChromatographServiceServer) AbortRun(context.Context, *AbortRun_Parameters) (*AbortRun_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortRun not implemented")
}
func (UnimplementedChromatographServiceServer) GetState(context.Context, *GetState_Parameters) (*GetState_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedChromatographServiceServer) mustEmbedUnimplementedChromatographServiceServer() {}
func (UnimplementedChromatographServiceServer) testEmbeddedByValue()                              {}

// UnsafeChromatographServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChromatographServiceServer will
// result in compilation errors.
type UnsafeChromatographServiceServer interface {
	mustEmbedUnimplementedChromatographServiceServer()
}

func RegisterChromatographServiceServer(s grpc.ServiceRegistrar, srv ChromatographServiceServer) {
	// If the following call panics, it indicates UnimplementedChromatographServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChromatographService_ServiceDesc, srv)
}

func _ChromatographService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRun_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).StartRun(ctx, req.(*StartRun_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_StopRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRun_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).StopRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_StopRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).StopRun(ctx, req.(*StopRun_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_PauseRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRun_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).PauseRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_PauseRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).PauseRun(ctx, req.(*PauseRun_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_ResumeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRun_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).ResumeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_ResumeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).ResumeRun(ctx, req.(*ResumeRun_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_AbortRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRun_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).AbortRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_AbortRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).AbortRun(ctx, req.(*AbortRun_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetState_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).GetState(ctx, req.(*GetState_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

// ChromatographService_ServiceDesc is the grpc.ServiceDesc for ChromatographService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChromatographService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sila2.org.silastandard.core.chromatographservice.v1.ChromatographService",
	HandlerType: (*ChromatographServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _ChromatographService_StartRun_Handler,
		},
		{
			MethodName: "StopRun",
			Handler:    _ChromatographService_StopRun_Handler,
		},
		{
			MethodName: "PauseRun",
			Handler:    _ChromatographService_PauseRun_Handler,
		},
		{
			MethodName: "ResumeRun",
			Handler:    _ChromatographService_ResumeRun_Handler,
		},
		{
			MethodName: "AbortRun",
			Handler:    _ChromatographService_AbortRun_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _ChromatographService_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chromatograph.proto",
}
