// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/chromatograph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodId      string                 `protobuf:"bytes,1,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunRequest) Reset() {
	*x = StartRunRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunRequest) ProtoMessage() {}

func (x *StartRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunRequest.ProtoReflect.Descriptor instead.
func (*StartRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{0}
}

func (x *StartRunRequest) GetMethodId() string {
	if x != nil {
		return x.MethodId
	}
	return ""
}

type StartRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunResponse) Reset() {
	*x = StartRunResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunResponse) ProtoMessage() {}

func (x *StartRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunResponse.ProtoReflect.Descriptor instead.
func (*StartRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{1}
}

func (x *StartRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunRequest) Reset() {
	*x = StopRunRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunRequest) ProtoMessage() {}

func (x *StopRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunRequest.ProtoReflect.Descriptor instead.
func (*StopRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{2}
}

type StopRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunResponse) Reset() {
	*x = StopRunResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunResponse) ProtoMessage() {}

func (x *StopRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunResponse.ProtoReflect.Descriptor instead.
func (*StopRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{3}
}

func (x *StopRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{4}
}

type GetStateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CurrentState     string                 `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	CycleCount       int32                  `protobuf:"varint,2,opt,name=cycle_count,json=cycleCount,proto3" json:"cycle_count,omitempty"`
	TargetCycleCount int32                  `protobuf:"varint,3,opt,name=target_cycle_count,json=targetCycleCount,proto3" json:"target_cycle_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{5}
}

func (x *GetStateResponse) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *GetStateResponse) GetCycleCount() int32 {
	if x != nil {
		return x.CycleCount
	}
	return 0
}

func (x *GetStateResponse) GetTargetCycleCount() int32 {
	if x != nil {
		return x.TargetCycleCount
	}
	return 0
}

type SetCycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CycleCount    int32                  `protobuf:"varint,1,opt,name=cycle_count,json=cycleCount,proto3" json:"cycle_count,omitempty"`           // Target total number of cycles
	CycleInterval float64                `protobuf:"fixed64,2,opt,name=cycle_interval,json=cycleInterval,proto3" json:"cycle_interval,omitempty"` // Interval between cycles in minutes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCycleRequest) Reset() {
	*x = SetCycleRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCycleRequest) ProtoMessage() {}

func (x *SetCycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCycleRequest.ProtoReflect.Descriptor instead.
func (*SetCycleRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{6}
}

func (x *SetCycleRequest) GetCycleCount() int32 {
	if x != nil {
		return x.CycleCount
	}
	return 0
}

func (x *SetCycleRequest) GetCycleInterval() float64 {
	if x != nil {
		return x.CycleInterval
	}
	return 0
}

type SetCycleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCycleResponse) Reset() {
	*x = SetCycleResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCycleResponse) ProtoMessage() {}

func (x *SetCycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCycleResponse.ProtoReflect.Descriptor instead.
func (*SetCycleResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{7}
}

func (x *SetCycleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCycleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_chromatograph_proto protoreflect.FileDescriptor

const file_proto_chromatograph_proto_rawDesc = "" +
	"\n" +
	"\x19proto/chromatograph.proto\x12\x13sila2.chromatograph\".\n" +
	"\x0fStartRunRequest\x12\x1b\n" +
	"\tmethod_id\x18\x01 \x01(\tR\bmethodId\"F\n" +
	"\x10StartRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eStopRunRequest\"E\n" +
	"\x0fStopRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fGetStateRequest\"\x86\x01\n" +
	"\x10GetStateResponse\x12#\n" +
	"\rcurrent_state\x18\x01 \x01(\tR\fcurrentState\x12\x1f\n" +
	"\vcycle_count\x18\x02 \x01(\x05R\n" +
	"cycleCount\x12,\n" +
	"\x12target_cycle_count\x18\x03 \x01(\x05R\x10targetCycleCount\"Y\n" +
	"\x0fSetCycleRequest\x12\x1f\n" +
	"\vcycle_count\x18\x01 \x01(\x05R\n" +
	"cycleCount\x12%\n" +
	"\x0ecycle_interval\x18\x02 \x01(\x01R\rcycleInterval\"F\n" +
	"\x10SetCycleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x89\x03\n" +
	"\x14ChromatographService\x12Y\n" +
	"\bStartRun\x12$.sila2.chromatograph.StartRunRequest\x1a%.sila2.chromatograph.StartRunResponse\"\x00\x12V\n" +
	"\aStopRun\x12#.sila2.chromatograph.StopRunRequest\x1a$.sila2.chromatograph.StopRunResponse\"\x00\x12Y\n" +
	"\bGetState\x12$.sila2.chromatograph.GetStateRequest\x1a%.sila2.chromatograph.GetStateResponse\"\x00\x12c\n" +
	"\x12SetCycleParameters\x12$.sila2.chromatograph.SetCycleRequest\x1a%.sila2.chromatograph.SetCycleResponse\"\x00B6Z4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_proto_chromatograph_proto_rawDescOnce sync.Once
	file_proto_chromatograph_proto_rawDescData []byte
)

func file_proto_chromatograph_proto_rawDescGZIP() []byte {
	file_proto_chromatograph_proto_rawDescOnce.Do(func() {
		file_proto_chromatograph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chromatograph_proto_rawDesc), len(file_proto_chromatograph_proto_rawDesc)))
	})
	return file_proto_chromatograph_proto_rawDescData
}

var file_proto_chromatograph_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_chromatograph_proto_goTypes = []any{
	(*StartRunRequest)(nil),  // 0: sila2.chromatograph.StartRunRequest
	(*StartRunResponse)(nil), // 1: sila2.chromatograph.StartRunResponse
	(*StopRunRequest)(nil),   // 2: sila2.chromatograph.StopRunRequest
	(*StopRunResponse)(nil),  // 3: sila2.chromatograph.StopRunResponse
	(*GetStateRequest)(nil),  // 4: sila2.chromatograph.GetStateRequest
	(*GetStateResponse)(nil), // 5: sila2.chromatograph.GetStateResponse
	(*SetCycleRequest)(nil),  // 6: sila2.chromatograph.SetCycleRequest
	(*SetCycleResponse)(nil), // 7: sila2.chromatograph.SetCycleResponse
}
var file_proto_chromatograph_proto_depIdxs = []int32{
	0, // 0: sila2.chromatograph.ChromatographService.StartRun:input_type -> sila2.chromatograph.StartRunRequest
	2, // 1: sila2.chromatograph.ChromatographService.StopRun:input_type -> sila2.chromatograph.StopRunRequest
	4, // 2: sila2.chromatograph.ChromatographService.GetState:input_type -> sila2.chromatograph.GetStateRequest
	6, // 3: sila2.chromatograph.ChromatographService.SetCycleParameters:input_type -> sila2.chromatograph.SetCycleRequest
	1, // 4: sila2.chromatograph.ChromatographService.StartRun:output_type -> sila2.chromatograph.StartRunResponse
	3, // 5: sila2.chromatograph.ChromatographService.StopRun:output_type -> sila2.chromatograph.StopRunResponse
	5, // 6: sila2.chromatograph.ChromatographService.GetState:output_type -> sila2.chromatograph.GetStateResponse
	7, // 7: sila2.chromatograph.ChromatographService.SetCycleParameters:output_type -> sila2.chromatograph.SetCycleResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chromatograph_proto_init() }
func file_proto_chromatograph_proto_init() {
	if File_proto_chromatograph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chromatograph_proto_rawDesc), len(file_proto_chromatograph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chromatograph_proto_goTypes,
		DependencyIndexes: file_proto_chromatograph_proto_depIdxs,
		MessageInfos:      file_proto_chromatograph_proto_msgTypes,
	}.Build()
	File_proto_chromatograph_proto = out.File
	file_proto_chromatograph_proto_goTypes = nil
	file_proto_chromatograph_proto_depIdxs = nil
}
