// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/chromatograph.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChromatographService_StartRun_FullMethodName                    = "/sila2.chromatograph.ChromatographService/StartRun"
	ChromatographService_StopRun_FullMethodName                     = "/sila2.chromatograph.ChromatographService/StopRun"
	ChromatographService_GetState_FullMethodName                    = "/sila2.chromatograph.ChromatographService/GetState"
	ChromatographService_SetCycleParameters_FullMethodName          = "/sila2.chromatograph.ChromatographService/SetCycleParameters"
	ChromatographService_Subscribe_AnalyticalResults_FullMethodName = "/sila2.chromatograph.ChromatographService/Subscribe_AnalyticalResults"
)

// ChromatographServiceClient is the client API for ChromatographService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The standard SiLA 2 service for a Chromatography device
type ChromatographServiceClient interface {
	// Starts a new chromatography run
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error)
	// Stops the current run
	StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*StopRunResponse, error)
	// Gets the current standard state of the digital twin
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	// Configures the cycle parameters for autonomous loop
	SetCycleParameters(ctx context.Context, in *SetCycleRequest, opts ...grpc.CallOption) (*SetCycleResponse, error)
	// Observable Property: Streams analytical results whenever they are updated
	Subscribe_AnalyticalResults(ctx context.Context, in *SubscribeAnalyticalResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeAnalyticalResultsResponse], error)
}

type chromatographServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChromatographServiceClient(cc grpc.ClientConnInterface) ChromatographServiceClient {
	return &chromatographServiceClient{cc}
}

func (c *chromatographServiceClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRunResponse)
	err := c.cc.Invoke(ctx, ChromatographService_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*StopRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRunResponse)
	err := c.cc.Invoke(ctx, ChromatographService_StopRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, ChromatographService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) SetCycleParameters(ctx context.Context, in *SetCycleRequest, opts ...grpc.CallOption) (*SetCycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCycleResponse)
	err := c.cc.Invoke(ctx, ChromatographService_SetCycleParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chromatographServiceClient) Subscribe_AnalyticalResults(ctx context.Context, in *SubscribeAnalyticalResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeAnalyticalResultsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChromatographService_ServiceDesc.Streams[0], ChromatographService_Subscribe_AnalyticalResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeAnalyticalResultsRequest, SubscribeAnalyticalResultsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChromatographService_Subscribe_AnalyticalResultsClient = grpc.ServerStreamingClient[SubscribeAnalyticalResultsResponse]

// ChromatographServiceServer is the server API for ChromatographService service.
// All implementations must embed UnimplementedChromatographServiceServer
// for forward compatibility.
//
// The standard SiLA 2 service for a Chromatography device
type ChromatographServiceServer interface {
	// Starts a new chromatography run
	StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error)
	// Stops the current run
	StopRun(context.Context, *StopRunRequest) (*StopRunResponse, error)
	// Gets the current standard state of the digital twin
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	// Configures the cycle parameters for autonomous loop
	SetCycleParameters(context.Context, *SetCycleRequest) (*SetCycleResponse, error)
	// Observable Property: Streams analytical results whenever they are updated
	Subscribe_AnalyticalResults(*SubscribeAnalyticalResultsRequest, grpc.ServerStreamingServer[SubscribeAnalyticalResultsResponse]) error
	mustEmbedUnimplementedChromatographServiceServer()
}

// UnimplementedChromatographServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChromatographServiceServer struct{}

func (UnimplementedChromatographServiceServer) StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedChromatographServiceServer) StopRun(context.Context, *StopRunRequest) (*StopRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRun not implemented")
}
func (UnimplementedChromatographServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedChromatographServiceServer) SetCycleParameters(context.Context, *SetCycleRequest) (*SetCycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCycleParameters not implemented")
}
func (UnimplementedChromatographServiceServer) Subscribe_AnalyticalResults(*SubscribeAnalyticalResultsRequest, grpc.ServerStreamingServer[SubscribeAnalyticalResultsResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe_AnalyticalResults not implemented")
}
func (UnimplementedChromatographServiceServer) mustEmbedUnimplementedChromatographServiceServer() {}
func (UnimplementedChromatographServiceServer) testEmbeddedByValue()                              {}

// UnsafeChromatographServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChromatographServiceServer will
// result in compilation errors.
type UnsafeChromatographServiceServer interface {
	mustEmbedUnimplementedChromatographServiceServer()
}

func RegisterChromatographServiceServer(s grpc.ServiceRegistrar, srv ChromatographServiceServer) {
	// If the following call panics, it indicates UnimplementedChromatographServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChromatographService_ServiceDesc, srv)
}

func _ChromatographService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_StopRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).StopRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_StopRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).StopRun(ctx, req.(*StopRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_SetCycleParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChromatographServiceServer).SetCycleParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChromatographService_SetCycleParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChromatographServiceServer).SetCycleParameters(ctx, req.(*SetCycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChromatographService_Subscribe_AnalyticalResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeAnalyticalResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChromatographServiceServer).Subscribe_AnalyticalResults(m, &grpc.GenericServerStream[SubscribeAnalyticalResultsRequest, SubscribeAnalyticalResultsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChromatographService_Subscribe_AnalyticalResultsServer = grpc.ServerStreamingServer[SubscribeAnalyticalResultsResponse]

// ChromatographService_ServiceDesc is the grpc.ServiceDesc for ChromatographService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChromatographService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sila2.chromatograph.ChromatographService",
	HandlerType: (*ChromatographServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _ChromatographService_StartRun_Handler,
		},
		{
			MethodName: "StopRun",
			Handler:    _ChromatographService_StopRun_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _ChromatographService_GetState_Handler,
		},
		{
			MethodName: "SetCycleParameters",
			Handler:    _ChromatographService_SetCycleParameters_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe_AnalyticalResults",
			Handler:       _ChromatographService_Subscribe_AnalyticalResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/chromatograph.proto",
}
