// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/chromatograph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeAnalyticalResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAnalyticalResultsRequest) Reset() {
	*x = SubscribeAnalyticalResultsRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAnalyticalResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAnalyticalResultsRequest) ProtoMessage() {}

func (x *SubscribeAnalyticalResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAnalyticalResultsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAnalyticalResultsRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{0}
}

type SubscribeAnalyticalResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]float64     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAnalyticalResultsResponse) Reset() {
	*x = SubscribeAnalyticalResultsResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAnalyticalResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAnalyticalResultsResponse) ProtoMessage() {}

func (x *SubscribeAnalyticalResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAnalyticalResultsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeAnalyticalResultsResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeAnalyticalResultsResponse) GetResults() map[string]float64 {
	if x != nil {
		return x.Results
	}
	return nil
}

type StartRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodId      string                 `protobuf:"bytes,1,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunRequest) Reset() {
	*x = StartRunRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunRequest) ProtoMessage() {}

func (x *StartRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunRequest.ProtoReflect.Descriptor instead.
func (*StartRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{2}
}

func (x *StartRunRequest) GetMethodId() string {
	if x != nil {
		return x.MethodId
	}
	return ""
}

type StartRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunResponse) Reset() {
	*x = StartRunResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunResponse) ProtoMessage() {}

func (x *StartRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunResponse.ProtoReflect.Descriptor instead.
func (*StartRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{3}
}

func (x *StartRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunRequest) Reset() {
	*x = StopRunRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunRequest) ProtoMessage() {}

func (x *StopRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunRequest.ProtoReflect.Descriptor instead.
func (*StopRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{4}
}

type StopRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunResponse) Reset() {
	*x = StopRunResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunResponse) ProtoMessage() {}

func (x *StopRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunResponse.ProtoReflect.Descriptor instead.
func (*StopRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{5}
}

func (x *StopRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PauseRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRunRequest) Reset() {
	*x = PauseRunRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRunRequest) ProtoMessage() {}

func (x *PauseRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRunRequest.ProtoReflect.Descriptor instead.
func (*PauseRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{6}
}

type PauseRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRunResponse) Reset() {
	*x = PauseRunResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRunResponse) ProtoMessage() {}

func (x *PauseRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRunResponse.ProtoReflect.Descriptor instead.
func (*PauseRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{7}
}

func (x *PauseRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResumeRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRunRequest) Reset() {
	*x = ResumeRunRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunRequest) ProtoMessage() {}

func (x *ResumeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunRequest.ProtoReflect.Descriptor instead.
func (*ResumeRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{8}
}

type ResumeRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRunResponse) Reset() {
	*x = ResumeRunResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRunResponse) ProtoMessage() {}

func (x *ResumeRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRunResponse.ProtoReflect.Descriptor instead.
func (*ResumeRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AbortRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRunRequest) Reset() {
	*x = AbortRunRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRunRequest) ProtoMessage() {}

func (x *AbortRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRunRequest.ProtoReflect.Descriptor instead.
func (*AbortRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{10}
}

type AbortRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRunResponse) Reset() {
	*x = AbortRunResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRunResponse) ProtoMessage() {}

func (x *AbortRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRunResponse.ProtoReflect.Descriptor instead.
func (*AbortRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{11}
}

func (x *AbortRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AbortRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{12}
}

type GetStateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CurrentState     string                 `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	CycleCount       int32                  `protobuf:"varint,2,opt,name=cycle_count,json=cycleCount,proto3" json:"cycle_count,omitempty"`
	TargetCycleCount int32                  `protobuf:"varint,3,opt,name=target_cycle_count,json=targetCycleCount,proto3" json:"target_cycle_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{13}
}

func (x *GetStateResponse) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *GetStateResponse) GetCycleCount() int32 {
	if x != nil {
		return x.CycleCount
	}
	return 0
}

func (x *GetStateResponse) GetTargetCycleCount() int32 {
	if x != nil {
		return x.TargetCycleCount
	}
	return 0
}

type SetCycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CycleCount    int32                  `protobuf:"varint,1,opt,name=cycle_count,json=cycleCount,proto3" json:"cycle_count,omitempty"`           // Target total number of cycles
	CycleInterval float64                `protobuf:"fixed64,2,opt,name=cycle_interval,json=cycleInterval,proto3" json:"cycle_interval,omitempty"` // Interval between cycles in minutes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCycleRequest) Reset() {
	*x = SetCycleRequest{}
	mi := &file_proto_chromatograph_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCycleRequest) ProtoMessage() {}

func (x *SetCycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCycleRequest.ProtoReflect.Descriptor instead.
func (*SetCycleRequest) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{14}
}

func (x *SetCycleRequest) GetCycleCount() int32 {
	if x != nil {
		return x.CycleCount
	}
	return 0
}

func (x *SetCycleRequest) GetCycleInterval() float64 {
	if x != nil {
		return x.CycleInterval
	}
	return 0
}

type SetCycleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCycleResponse) Reset() {
	*x = SetCycleResponse{}
	mi := &file_proto_chromatograph_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCycleResponse) ProtoMessage() {}

func (x *SetCycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chromatograph_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCycleResponse.ProtoReflect.Descriptor instead.
func (*SetCycleResponse) Descriptor() ([]byte, []int) {
	return file_proto_chromatograph_proto_rawDescGZIP(), []int{15}
}

func (x *SetCycleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetCycleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_chromatograph_proto protoreflect.FileDescriptor

const file_proto_chromatograph_proto_rawDesc = "" +
	"\n" +
	"\x19proto/chromatograph.proto\x12\x13sila2.chromatograph\"#\n" +
	"!SubscribeAnalyticalResultsRequest\"\xc0\x01\n" +
	"\"SubscribeAnalyticalResultsResponse\x12^\n" +
	"\aresults\x18\x01 \x03(\v2D.sila2.chromatograph.SubscribeAnalyticalResultsResponse.ResultsEntryR\aresults\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\".\n" +
	"\x0fStartRunRequest\x12\x1b\n" +
	"\tmethod_id\x18\x01 \x01(\tR\bmethodId\"F\n" +
	"\x10StartRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eStopRunRequest\"E\n" +
	"\x0fStopRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fPauseRunRequest\"F\n" +
	"\x10PauseRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10ResumeRunRequest\"G\n" +
	"\x11ResumeRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fAbortRunRequest\"F\n" +
	"\x10AbortRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fGetStateRequest\"\x86\x01\n" +
	"\x10GetStateResponse\x12#\n" +
	"\rcurrent_state\x18\x01 \x01(\tR\fcurrentState\x12\x1f\n" +
	"\vcycle_count\x18\x02 \x01(\x05R\n" +
	"cycleCount\x12,\n" +
	"\x12target_cycle_count\x18\x03 \x01(\x05R\x10targetCycleCount\"Y\n" +
	"\x0fSetCycleRequest\x12\x1f\n" +
	"\vcycle_count\x18\x01 \x01(\x05R\n" +
	"cycleCount\x12%\n" +
	"\x0ecycle_interval\x18\x02 \x01(\x01R\rcycleInterval\"F\n" +
	"\x10SetCycleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb2\x06\n" +
	"\x14ChromatographService\x12Y\n" +
	"\bStartRun\x12$.sila2.chromatograph.StartRunRequest\x1a%.sila2.chromatograph.StartRunResponse\"\x00\x12V\n" +
	"\aStopRun\x12#.sila2.chromatograph.StopRunRequest\x1a$.sila2.chromatograph.StopRunResponse\"\x00\x12Y\n" +
	"\bPauseRun\x12$.sila2.chromatograph.PauseRunRequest\x1a%.sila2.chromatograph.PauseRunResponse\"\x00\x12\\\n" +
	"\tResumeRun\x12%.sila2.chromatograph.ResumeRunRequest\x1a&.sila2.chromatograph.ResumeRunResponse\"\x00\x12Y\n" +
	"\bAbortRun\x12$.sila2.chromatograph.AbortRunRequest\x1a%.sila2.chromatograph.AbortRunResponse\"\x00\x12Y\n" +
	"\bGetState\x12$.sila2.chromatograph.GetStateRequest\x1a%.sila2.chromatograph.GetStateResponse\"\x00\x12c\n" +
	"\x12SetCycleParameters\x12$.sila2.chromatograph.SetCycleRequest\x1a%.sila2.chromatograph.SetCycleResponse\"\x00\x12\x92\x01\n" +
	"\x1bSubscribe_AnalyticalResults\x126.sila2.chromatograph.SubscribeAnalyticalResultsRequest\x1a7.sila2.chromatograph.SubscribeAnalyticalResultsResponse\"\x000\x01B6Z4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_proto_chromatograph_proto_rawDescOnce sync.Once
	file_proto_chromatograph_proto_rawDescData []byte
)

func file_proto_chromatograph_proto_rawDescGZIP() []byte {
	file_proto_chromatograph_proto_rawDescOnce.Do(func() {
		file_proto_chromatograph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chromatograph_proto_rawDesc), len(file_proto_chromatograph_proto_rawDesc)))
	})
	return file_proto_chromatograph_proto_rawDescData
}

var file_proto_chromatograph_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_chromatograph_proto_goTypes = []any{
	(*SubscribeAnalyticalResultsRequest)(nil),  // 0: sila2.chromatograph.SubscribeAnalyticalResultsRequest
	(*SubscribeAnalyticalResultsResponse)(nil), // 1: sila2.chromatograph.SubscribeAnalyticalResultsResponse
	(*StartRunRequest)(nil),                    // 2: sila2.chromatograph.StartRunRequest
	(*StartRunResponse)(nil),                   // 3: sila2.chromatograph.StartRunResponse
	(*StopRunRequest)(nil),                     // 4: sila2.chromatograph.StopRunRequest
	(*StopRunResponse)(nil),                    // 5: sila2.chromatograph.StopRunResponse
	(*PauseRunRequest)(nil),                    // 6: sila2.chromatograph.PauseRunRequest
	(*PauseRunResponse)(nil),                   // 7: sila2.chromatograph.PauseRunResponse
	(*ResumeRunRequest)(nil),                   // 8: sila2.chromatograph.ResumeRunRequest
	(*ResumeRunResponse)(nil),                  // 9: sila2.chromatograph.ResumeRunResponse
	(*AbortRunRequest)(nil),                    // 10: sila2.chromatograph.AbortRunRequest
	(*AbortRunResponse)(nil),                   // 11: sila2.chromatograph.AbortRunResponse
	(*GetStateRequest)(nil),                    // 12: sila2.chromatograph.GetStateRequest
	(*GetStateResponse)(nil),                   // 13: sila2.chromatograph.GetStateResponse
	(*SetCycleRequest)(nil),                    // 14: sila2.chromatograph.SetCycleRequest
	(*SetCycleResponse)(nil),                   // 15: sila2.chromatograph.SetCycleResponse
	nil,                                        // 16: sila2.chromatograph.SubscribeAnalyticalResultsResponse.ResultsEntry
}
var file_proto_chromatograph_proto_depIdxs = []int32{
	16, // 0: sila2.chromatograph.SubscribeAnalyticalResultsResponse.results:type_name -> sila2.chromatograph.SubscribeAnalyticalResultsResponse.ResultsEntry
	2,  // 1: sila2.chromatograph.ChromatographService.StartRun:input_type -> sila2.chromatograph.StartRunRequest
	4,  // 2: sila2.chromatograph.ChromatographService.StopRun:input_type -> sila2.chromatograph.StopRunRequest
	6,  // 3: sila2.chromatograph.ChromatographService.PauseRun:input_type -> sila2.chromatograph.PauseRunRequest
	8,  // 4: sila2.chromatograph.ChromatographService.ResumeRun:input_type -> sila2.chromatograph.ResumeRunRequest
	10, // 5: sila2.chromatograph.ChromatographService.AbortRun:input_type -> sila2.chromatograph.AbortRunRequest
	12, // 6: sila2.chromatograph.ChromatographService.GetState:input_type -> sila2.chromatograph.GetStateRequest
	14, // 7: sila2.chromatograph.ChromatographService.SetCycleParameters:input_type -> sila2.chromatograph.SetCycleRequest
	0,  // 8: sila2.chromatograph.ChromatographService.Subscribe_AnalyticalResults:input_type -> sila2.chromatograph.SubscribeAnalyticalResultsRequest
	3,  // 9: sila2.chromatograph.ChromatographService.StartRun:output_type -> sila2.chromatograph.StartRunResponse
	5,  // 10: sila2.chromatograph.ChromatographService.StopRun:output_type -> sila2.chromatograph.StopRunResponse
	7,  // 11: sila2.chromatograph.ChromatographService.PauseRun:output_type -> sila2.chromatograph.PauseRunResponse
	9,  // 12: sila2.chromatograph.ChromatographService.ResumeRun:output_type -> sila2.chromatograph.ResumeRunResponse
	11, // 13: sila2.chromatograph.ChromatographService.AbortRun:output_type -> sila2.chromatograph.AbortRunResponse
	13, // 14: sila2.chromatograph.ChromatographService.GetState:output_type -> sila2.chromatograph.GetStateResponse
	15, // 15: sila2.chromatograph.ChromatographService.SetCycleParameters:output_type -> sila2.chromatograph.SetCycleResponse
	1,  // 16: sila2.chromatograph.ChromatographService.Subscribe_AnalyticalResults:output_type -> sila2.chromatograph.SubscribeAnalyticalResultsResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chromatograph_proto_init() }
func file_proto_chromatograph_proto_init() {
	if File_proto_chromatograph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chromatograph_proto_rawDesc), len(file_proto_chromatograph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chromatograph_proto_goTypes,
		DependencyIndexes: file_proto_chromatograph_proto_depIdxs,
		MessageInfos:      file_proto_chromatograph_proto_msgTypes,
	}.Build()
	File_proto_chromatograph_proto = out.File
	file_proto_chromatograph_proto_goTypes = nil
	file_proto_chromatograph_proto_depIdxs = nil
}
