// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: detector.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlameIonizationDetectorService_Ignite_FullMethodName       = "/sila2.custom.detectorservice.v1.FlameIonizationDetectorService/Ignite"
	FlameIonizationDetectorService_IgniteConfig_FullMethodName = "/sila2.custom.detectorservice.v1.FlameIonizationDetectorService/IgniteConfig"
)

// FlameIonizationDetectorServiceClient is the client API for FlameIonizationDetectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlameIonizationDetectorServiceClient interface {
	Ignite(ctx context.Context, in *IgniteRequest, opts ...grpc.CallOption) (*IgniteResponse, error)
	IgniteConfig(ctx context.Context, in *IgniteConfigRequest, opts ...grpc.CallOption) (*IgniteConfigResponse, error)
}

type flameIonizationDetectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlameIonizationDetectorServiceClient(cc grpc.ClientConnInterface) FlameIonizationDetectorServiceClient {
	return &flameIonizationDetectorServiceClient{cc}
}

func (c *flameIonizationDetectorServiceClient) Ignite(ctx context.Context, in *IgniteRequest, opts ...grpc.CallOption) (*IgniteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IgniteResponse)
	err := c.cc.Invoke(ctx, FlameIonizationDetectorService_Ignite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flameIonizationDetectorServiceClient) IgniteConfig(ctx context.Context, in *IgniteConfigRequest, opts ...grpc.CallOption) (*IgniteConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IgniteConfigResponse)
	err := c.cc.Invoke(ctx, FlameIonizationDetectorService_IgniteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlameIonizationDetectorServiceServer is the server API for FlameIonizationDetectorService service.
// All implementations must embed UnimplementedFlameIonizationDetectorServiceServer
// for forward compatibility.
type FlameIonizationDetectorServiceServer interface {
	Ignite(context.Context, *IgniteRequest) (*IgniteResponse, error)
	IgniteConfig(context.Context, *IgniteConfigRequest) (*IgniteConfigResponse, error)
	mustEmbedUnimplementedFlameIonizationDetectorServiceServer()
}

// UnimplementedFlameIonizationDetectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlameIonizationDetectorServiceServer struct{}

func (UnimplementedFlameIonizationDetectorServiceServer) Ignite(context.Context, *IgniteRequest) (*IgniteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ignite not implemented")
}
func (UnimplementedFlameIonizationDetectorServiceServer) IgniteConfig(context.Context, *IgniteConfigRequest) (*IgniteConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IgniteConfig not implemented")
}
func (UnimplementedFlameIonizationDetectorServiceServer) mustEmbedUnimplementedFlameIonizationDetectorServiceServer() {
}
func (UnimplementedFlameIonizationDetectorServiceServer) testEmbeddedByValue() {}

// UnsafeFlameIonizationDetectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlameIonizationDetectorServiceServer will
// result in compilation errors.
type UnsafeFlameIonizationDetectorServiceServer interface {
	mustEmbedUnimplementedFlameIonizationDetectorServiceServer()
}

func RegisterFlameIonizationDetectorServiceServer(s grpc.ServiceRegistrar, srv FlameIonizationDetectorServiceServer) {
	// If the following call panics, it indicates UnimplementedFlameIonizationDetectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlameIonizationDetectorService_ServiceDesc, srv)
}

func _FlameIonizationDetectorService_Ignite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IgniteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlameIonizationDetectorServiceServer).Ignite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlameIonizationDetectorService_Ignite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlameIonizationDetectorServiceServer).Ignite(ctx, req.(*IgniteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlameIonizationDetectorService_IgniteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IgniteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlameIonizationDetectorServiceServer).IgniteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlameIonizationDetectorService_IgniteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlameIonizationDetectorServiceServer).IgniteConfig(ctx, req.(*IgniteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlameIonizationDetectorService_ServiceDesc is the grpc.ServiceDesc for FlameIonizationDetectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlameIonizationDetectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sila2.custom.detectorservice.v1.FlameIonizationDetectorService",
	HandlerType: (*FlameIonizationDetectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ignite",
			Handler:    _FlameIonizationDetectorService_Ignite_Handler,
		},
		{
			MethodName: "IgniteConfig",
			Handler:    _FlameIonizationDetectorService_IgniteConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detector.proto",
}

const (
	ThermalConductivityDetectorService_SetBridge_FullMethodName = "/sila2.custom.detectorservice.v1.ThermalConductivityDetectorService/SetBridge"
	ThermalConductivityDetectorService_Zeroing_FullMethodName   = "/sila2.custom.detectorservice.v1.ThermalConductivityDetectorService/Zeroing"
	ThermalConductivityDetectorService_State_FullMethodName     = "/sila2.custom.detectorservice.v1.ThermalConductivityDetectorService/State"
)

// ThermalConductivityDetectorServiceClient is the client API for ThermalConductivityDetectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThermalConductivityDetectorServiceClient interface {
	SetBridge(ctx context.Context, in *SetBridgeRequest, opts ...grpc.CallOption) (*SetBridgeResponse, error)
	Zeroing(ctx context.Context, in *ZeroingRequest, opts ...grpc.CallOption) (*ZeroingResponse, error)
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
}

type thermalConductivityDetectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThermalConductivityDetectorServiceClient(cc grpc.ClientConnInterface) ThermalConductivityDetectorServiceClient {
	return &thermalConductivityDetectorServiceClient{cc}
}

func (c *thermalConductivityDetectorServiceClient) SetBridge(ctx context.Context, in *SetBridgeRequest, opts ...grpc.CallOption) (*SetBridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBridgeResponse)
	err := c.cc.Invoke(ctx, ThermalConductivityDetectorService_SetBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thermalConductivityDetectorServiceClient) Zeroing(ctx context.Context, in *ZeroingRequest, opts ...grpc.CallOption) (*ZeroingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZeroingResponse)
	err := c.cc.Invoke(ctx, ThermalConductivityDetectorService_Zeroing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thermalConductivityDetectorServiceClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, ThermalConductivityDetectorService_State_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThermalConductivityDetectorServiceServer is the server API for ThermalConductivityDetectorService service.
// All implementations must embed UnimplementedThermalConductivityDetectorServiceServer
// for forward compatibility.
type ThermalConductivityDetectorServiceServer interface {
	SetBridge(context.Context, *SetBridgeRequest) (*SetBridgeResponse, error)
	Zeroing(context.Context, *ZeroingRequest) (*ZeroingResponse, error)
	State(context.Context, *StateRequest) (*StateResponse, error)
	mustEmbedUnimplementedThermalConductivityDetectorServiceServer()
}

// UnimplementedThermalConductivityDetectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThermalConductivityDetectorServiceServer struct{}

func (UnimplementedThermalConductivityDetectorServiceServer) SetBridge(context.Context, *SetBridgeRequest) (*SetBridgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBridge not implemented")
}
func (UnimplementedThermalConductivityDetectorServiceServer) Zeroing(context.Context, *ZeroingRequest) (*ZeroingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Zeroing not implemented")
}
func (UnimplementedThermalConductivityDetectorServiceServer) State(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method State not implemented")
}
func (UnimplementedThermalConductivityDetectorServiceServer) mustEmbedUnimplementedThermalConductivityDetectorServiceServer() {
}
func (UnimplementedThermalConductivityDetectorServiceServer) testEmbeddedByValue() {}

// UnsafeThermalConductivityDetectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThermalConductivityDetectorServiceServer will
// result in compilation errors.
type UnsafeThermalConductivityDetectorServiceServer interface {
	mustEmbedUnimplementedThermalConductivityDetectorServiceServer()
}

func RegisterThermalConductivityDetectorServiceServer(s grpc.ServiceRegistrar, srv ThermalConductivityDetectorServiceServer) {
	// If the following call panics, it indicates UnimplementedThermalConductivityDetectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThermalConductivityDetectorService_ServiceDesc, srv)
}

func _ThermalConductivityDetectorService_SetBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThermalConductivityDetectorServiceServer).SetBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThermalConductivityDetectorService_SetBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThermalConductivityDetectorServiceServer).SetBridge(ctx, req.(*SetBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThermalConductivityDetectorService_Zeroing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZeroingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThermalConductivityDetectorServiceServer).Zeroing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThermalConductivityDetectorService_Zeroing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThermalConductivityDetectorServiceServer).Zeroing(ctx, req.(*ZeroingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThermalConductivityDetectorService_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThermalConductivityDetectorServiceServer).State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThermalConductivityDetectorService_State_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThermalConductivityDetectorServiceServer).State(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThermalConductivityDetectorService_ServiceDesc is the grpc.ServiceDesc for ThermalConductivityDetectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThermalConductivityDetectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sila2.custom.detectorservice.v1.ThermalConductivityDetectorService",
	HandlerType: (*ThermalConductivityDetectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBridge",
			Handler:    _ThermalConductivityDetectorService_SetBridge_Handler,
		},
		{
			MethodName: "Zeroing",
			Handler:    _ThermalConductivityDetectorService_Zeroing_Handler,
		},
		{
			MethodName: "State",
			Handler:    _ThermalConductivityDetectorService_State_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detector.proto",
}
