// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: detector.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IgniteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgniteRequest) Reset() {
	*x = IgniteRequest{}
	mi := &file_detector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgniteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgniteRequest) ProtoMessage() {}

func (x *IgniteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgniteRequest.ProtoReflect.Descriptor instead.
func (*IgniteRequest) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{0}
}

func (x *IgniteRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type IgniteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgniteResponse) Reset() {
	*x = IgniteResponse{}
	mi := &file_detector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgniteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgniteResponse) ProtoMessage() {}

func (x *IgniteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgniteResponse.ProtoReflect.Descriptor instead.
func (*IgniteResponse) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{1}
}

func (x *IgniteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IgniteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IgniteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Threshold1    float64                `protobuf:"fixed64,2,opt,name=threshold1,proto3" json:"threshold1,omitempty"`
	Threshold2    float64                `protobuf:"fixed64,3,opt,name=threshold2,proto3" json:"threshold2,omitempty"`
	Duration      float64                `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgniteConfigRequest) Reset() {
	*x = IgniteConfigRequest{}
	mi := &file_detector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgniteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgniteConfigRequest) ProtoMessage() {}

func (x *IgniteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgniteConfigRequest.ProtoReflect.Descriptor instead.
func (*IgniteConfigRequest) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{2}
}

func (x *IgniteConfigRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IgniteConfigRequest) GetThreshold1() float64 {
	if x != nil {
		return x.Threshold1
	}
	return 0
}

func (x *IgniteConfigRequest) GetThreshold2() float64 {
	if x != nil {
		return x.Threshold2
	}
	return 0
}

func (x *IgniteConfigRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type IgniteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgniteConfigResponse) Reset() {
	*x = IgniteConfigResponse{}
	mi := &file_detector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgniteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgniteConfigResponse) ProtoMessage() {}

func (x *IgniteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgniteConfigResponse.ProtoReflect.Descriptor instead.
func (*IgniteConfigResponse) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{3}
}

func (x *IgniteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IgniteConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Current       int32                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"` // mA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBridgeRequest) Reset() {
	*x = SetBridgeRequest{}
	mi := &file_detector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBridgeRequest) ProtoMessage() {}

func (x *SetBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBridgeRequest.ProtoReflect.Descriptor instead.
func (*SetBridgeRequest) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{4}
}

func (x *SetBridgeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetBridgeRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

type SetBridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBridgeResponse) Reset() {
	*x = SetBridgeResponse{}
	mi := &file_detector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBridgeResponse) ProtoMessage() {}

func (x *SetBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBridgeResponse.ProtoReflect.Descriptor instead.
func (*SetBridgeResponse) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{5}
}

func (x *SetBridgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetBridgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ZeroingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroingRequest) Reset() {
	*x = ZeroingRequest{}
	mi := &file_detector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroingRequest) ProtoMessage() {}

func (x *ZeroingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroingRequest.ProtoReflect.Descriptor instead.
func (*ZeroingRequest) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{6}
}

func (x *ZeroingRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ZeroingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroingResponse) Reset() {
	*x = ZeroingResponse{}
	mi := &file_detector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroingResponse) ProtoMessage() {}

func (x *ZeroingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroingResponse.ProtoReflect.Descriptor instead.
func (*ZeroingResponse) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{7}
}

func (x *ZeroingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ZeroingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_detector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{8}
}

func (x *StateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	CurrentValue  float64                `protobuf:"fixed64,2,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_detector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_detector_proto_rawDescGZIP(), []int{9}
}

func (x *StateResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *StateResponse) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

var File_detector_proto protoreflect.FileDescriptor

const file_detector_proto_rawDesc = "" +
	"\n" +
	"\x0edetector.proto\x12\x0esila2.detector\",\n" +
	"\rIgniteRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"D\n" +
	"\x0eIgniteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8e\x01\n" +
	"\x13IgniteConfigRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1e\n" +
	"\n" +
	"threshold1\x18\x02 \x01(\x01R\n" +
	"threshold1\x12\x1e\n" +
	"\n" +
	"threshold2\x18\x03 \x01(\x01R\n" +
	"threshold2\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x01R\bduration\"J\n" +
	"\x14IgniteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x10SetBridgeRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x05R\acurrent\"G\n" +
	"\x11SetBridgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x0eZeroingRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"E\n" +
	"\x0fZeroingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\fStateRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"O\n" +
	"\rStateResponse\x12\x19\n" +
	"\bis_ready\x18\x01 \x01(\bR\aisReady\x12#\n" +
	"\rcurrent_value\x18\x02 \x01(\x01R\fcurrentValue2\xc8\x01\n" +
	"\x1eFlameIonizationDetectorService\x12I\n" +
	"\x06Ignite\x12\x1d.sila2.detector.IgniteRequest\x1a\x1e.sila2.detector.IgniteResponse\"\x00\x12[\n" +
	"\fIgniteConfig\x12#.sila2.detector.IgniteConfigRequest\x1a$.sila2.detector.IgniteConfigResponse\"\x002\x8e\x02\n" +
	"\"ThermalConductivityDetectorService\x12R\n" +
	"\tSetBridge\x12 .sila2.detector.SetBridgeRequest\x1a!.sila2.detector.SetBridgeResponse\"\x00\x12L\n" +
	"\aZeroing\x12\x1e.sila2.detector.ZeroingRequest\x1a\x1f.sila2.detector.ZeroingResponse\"\x00\x12F\n" +
	"\x05State\x12\x1c.sila2.detector.StateRequest\x1a\x1d.sila2.detector.StateResponse\"\x00B6Z4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_detector_proto_rawDescOnce sync.Once
	file_detector_proto_rawDescData []byte
)

func file_detector_proto_rawDescGZIP() []byte {
	file_detector_proto_rawDescOnce.Do(func() {
		file_detector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detector_proto_rawDesc), len(file_detector_proto_rawDesc)))
	})
	return file_detector_proto_rawDescData
}

var file_detector_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_detector_proto_goTypes = []any{
	(*IgniteRequest)(nil),        // 0: sila2.detector.IgniteRequest
	(*IgniteResponse)(nil),       // 1: sila2.detector.IgniteResponse
	(*IgniteConfigRequest)(nil),  // 2: sila2.detector.IgniteConfigRequest
	(*IgniteConfigResponse)(nil), // 3: sila2.detector.IgniteConfigResponse
	(*SetBridgeRequest)(nil),     // 4: sila2.detector.SetBridgeRequest
	(*SetBridgeResponse)(nil),    // 5: sila2.detector.SetBridgeResponse
	(*ZeroingRequest)(nil),       // 6: sila2.detector.ZeroingRequest
	(*ZeroingResponse)(nil),      // 7: sila2.detector.ZeroingResponse
	(*StateRequest)(nil),         // 8: sila2.detector.StateRequest
	(*StateResponse)(nil),        // 9: sila2.detector.StateResponse
}
var file_detector_proto_depIdxs = []int32{
	0, // 0: sila2.detector.FlameIonizationDetectorService.Ignite:input_type -> sila2.detector.IgniteRequest
	2, // 1: sila2.detector.FlameIonizationDetectorService.IgniteConfig:input_type -> sila2.detector.IgniteConfigRequest
	4, // 2: sila2.detector.ThermalConductivityDetectorService.SetBridge:input_type -> sila2.detector.SetBridgeRequest
	6, // 3: sila2.detector.ThermalConductivityDetectorService.Zeroing:input_type -> sila2.detector.ZeroingRequest
	8, // 4: sila2.detector.ThermalConductivityDetectorService.State:input_type -> sila2.detector.StateRequest
	1, // 5: sila2.detector.FlameIonizationDetectorService.Ignite:output_type -> sila2.detector.IgniteResponse
	3, // 6: sila2.detector.FlameIonizationDetectorService.IgniteConfig:output_type -> sila2.detector.IgniteConfigResponse
	5, // 7: sila2.detector.ThermalConductivityDetectorService.SetBridge:output_type -> sila2.detector.SetBridgeResponse
	7, // 8: sila2.detector.ThermalConductivityDetectorService.Zeroing:output_type -> sila2.detector.ZeroingResponse
	9, // 9: sila2.detector.ThermalConductivityDetectorService.State:output_type -> sila2.detector.StateResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_detector_proto_init() }
func file_detector_proto_init() {
	if File_detector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detector_proto_rawDesc), len(file_detector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_detector_proto_goTypes,
		DependencyIndexes: file_detector_proto_depIdxs,
		MessageInfos:      file_detector_proto_msgTypes,
	}.Build()
	File_detector_proto = out.File
	file_detector_proto_goTypes = nil
	file_detector_proto_depIdxs = nil
}
