// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pneumatic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetTargetPressureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Channel        string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // e.g., carrier, h2, air
	TargetPressure float64                `protobuf:"fixed64,3,opt,name=target_pressure,json=targetPressure,proto3" json:"target_pressure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetTargetPressureRequest) Reset() {
	*x = SetTargetPressureRequest{}
	mi := &file_pneumatic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTargetPressureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTargetPressureRequest) ProtoMessage() {}

func (x *SetTargetPressureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pneumatic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTargetPressureRequest.ProtoReflect.Descriptor instead.
func (*SetTargetPressureRequest) Descriptor() ([]byte, []int) {
	return file_pneumatic_proto_rawDescGZIP(), []int{0}
}

func (x *SetTargetPressureRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetTargetPressureRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SetTargetPressureRequest) GetTargetPressure() float64 {
	if x != nil {
		return x.TargetPressure
	}
	return 0
}

type SetTargetPressureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTargetPressureResponse) Reset() {
	*x = SetTargetPressureResponse{}
	mi := &file_pneumatic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTargetPressureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTargetPressureResponse) ProtoMessage() {}

func (x *SetTargetPressureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pneumatic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTargetPressureResponse.ProtoReflect.Descriptor instead.
func (*SetTargetPressureResponse) Descriptor() ([]byte, []int) {
	return file_pneumatic_proto_rawDescGZIP(), []int{1}
}

func (x *SetTargetPressureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTargetPressureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pneumatic_proto protoreflect.FileDescriptor

const file_pneumatic_proto_rawDesc = "" +
	"\n" +
	"\x0fpneumatic.proto\x12 sila2.custom.pneumaticservice.v1\"z\n" +
	"\x18SetTargetPressureRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12'\n" +
	"\x0ftarget_pressure\x18\x03 \x01(\x01R\x0etargetPressure\"O\n" +
	"\x19SetTargetPressureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\x01\n" +
	"\x1aPneumaticControllerService\x12\x8e\x01\n" +
	"\x11SetTargetPressure\x12:.sila2.custom.pneumaticservice.v1.SetTargetPressureRequest\x1a;.sila2.custom.pneumaticservice.v1.SetTargetPressureResponse\"\x00B6Z4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_pneumatic_proto_rawDescOnce sync.Once
	file_pneumatic_proto_rawDescData []byte
)

func file_pneumatic_proto_rawDescGZIP() []byte {
	file_pneumatic_proto_rawDescOnce.Do(func() {
		file_pneumatic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pneumatic_proto_rawDesc), len(file_pneumatic_proto_rawDesc)))
	})
	return file_pneumatic_proto_rawDescData
}

var file_pneumatic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pneumatic_proto_goTypes = []any{
	(*SetTargetPressureRequest)(nil),  // 0: sila2.custom.pneumaticservice.v1.SetTargetPressureRequest
	(*SetTargetPressureResponse)(nil), // 1: sila2.custom.pneumaticservice.v1.SetTargetPressureResponse
}
var file_pneumatic_proto_depIdxs = []int32{
	0, // 0: sila2.custom.pneumaticservice.v1.PneumaticControllerService.SetTargetPressure:input_type -> sila2.custom.pneumaticservice.v1.SetTargetPressureRequest
	1, // 1: sila2.custom.pneumaticservice.v1.PneumaticControllerService.SetTargetPressure:output_type -> sila2.custom.pneumaticservice.v1.SetTargetPressureResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pneumatic_proto_init() }
func file_pneumatic_proto_init() {
	if File_pneumatic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pneumatic_proto_rawDesc), len(file_pneumatic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pneumatic_proto_goTypes,
		DependencyIndexes: file_pneumatic_proto_depIdxs,
		MessageInfos:      file_pneumatic_proto_msgTypes,
	}.Build()
	File_pneumatic_proto = out.File
	file_pneumatic_proto_goTypes = nil
	file_pneumatic_proto_depIdxs = nil
}
