// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: pneumatic.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PneumaticControllerService_SetTargetPressure_FullMethodName = "/sila2.pneumatic.PneumaticControllerService/SetTargetPressure"
)

// PneumaticControllerServiceClient is the client API for PneumaticControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PneumaticControllerServiceClient interface {
	SetTargetPressure(ctx context.Context, in *SetTargetPressureRequest, opts ...grpc.CallOption) (*SetTargetPressureResponse, error)
}

type pneumaticControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPneumaticControllerServiceClient(cc grpc.ClientConnInterface) PneumaticControllerServiceClient {
	return &pneumaticControllerServiceClient{cc}
}

func (c *pneumaticControllerServiceClient) SetTargetPressure(ctx context.Context, in *SetTargetPressureRequest, opts ...grpc.CallOption) (*SetTargetPressureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTargetPressureResponse)
	err := c.cc.Invoke(ctx, PneumaticControllerService_SetTargetPressure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PneumaticControllerServiceServer is the server API for PneumaticControllerService service.
// All implementations must embed UnimplementedPneumaticControllerServiceServer
// for forward compatibility.
type PneumaticControllerServiceServer interface {
	SetTargetPressure(context.Context, *SetTargetPressureRequest) (*SetTargetPressureResponse, error)
	mustEmbedUnimplementedPneumaticControllerServiceServer()
}

// UnimplementedPneumaticControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPneumaticControllerServiceServer struct{}

func (UnimplementedPneumaticControllerServiceServer) SetTargetPressure(context.Context, *SetTargetPressureRequest) (*SetTargetPressureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTargetPressure not implemented")
}
func (UnimplementedPneumaticControllerServiceServer) mustEmbedUnimplementedPneumaticControllerServiceServer() {
}
func (UnimplementedPneumaticControllerServiceServer) testEmbeddedByValue() {}

// UnsafePneumaticControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PneumaticControllerServiceServer will
// result in compilation errors.
type UnsafePneumaticControllerServiceServer interface {
	mustEmbedUnimplementedPneumaticControllerServiceServer()
}

func RegisterPneumaticControllerServiceServer(s grpc.ServiceRegistrar, srv PneumaticControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedPneumaticControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PneumaticControllerService_ServiceDesc, srv)
}

func _PneumaticControllerService_SetTargetPressure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTargetPressureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PneumaticControllerServiceServer).SetTargetPressure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PneumaticControllerService_SetTargetPressure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PneumaticControllerServiceServer).SetTargetPressure(ctx, req.(*SetTargetPressureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PneumaticControllerService_ServiceDesc is the grpc.ServiceDesc for PneumaticControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PneumaticControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sila2.pneumatic.PneumaticControllerService",
	HandlerType: (*PneumaticControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTargetPressure",
			Handler:    _PneumaticControllerService_SetTargetPressure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pneumatic.proto",
}
