// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: SiLAService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeatureDefinition_Parameters struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeatureIdentifier *String                `protobuf:"bytes,1,opt,name=FeatureIdentifier,proto3" json:"FeatureIdentifier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetFeatureDefinition_Parameters) Reset() {
	*x = GetFeatureDefinition_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureDefinition_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureDefinition_Parameters) ProtoMessage() {}

func (x *GetFeatureDefinition_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureDefinition_Parameters.ProtoReflect.Descriptor instead.
func (*GetFeatureDefinition_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeatureDefinition_Parameters) GetFeatureIdentifier() *String {
	if x != nil {
		return x.FeatureIdentifier
	}
	return nil
}

type GetFeatureDefinition_Responses struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeatureDefinition *String                `protobuf:"bytes,1,opt,name=FeatureDefinition,proto3" json:"FeatureDefinition,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetFeatureDefinition_Responses) Reset() {
	*x = GetFeatureDefinition_Responses{}
	mi := &file_SiLAService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureDefinition_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureDefinition_Responses) ProtoMessage() {}

func (x *GetFeatureDefinition_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureDefinition_Responses.ProtoReflect.Descriptor instead.
func (*GetFeatureDefinition_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeatureDefinition_Responses) GetFeatureDefinition() *String {
	if x != nil {
		return x.FeatureDefinition
	}
	return nil
}

type SetServerName_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    *String                `protobuf:"bytes,1,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServerName_Parameters) Reset() {
	*x = SetServerName_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServerName_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServerName_Parameters) ProtoMessage() {}

func (x *SetServerName_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServerName_Parameters.ProtoReflect.Descriptor instead.
func (*SetServerName_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{2}
}

func (x *SetServerName_Parameters) GetServerName() *String {
	if x != nil {
		return x.ServerName
	}
	return nil
}

type SetServerName_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServerName_Responses) Reset() {
	*x = SetServerName_Responses{}
	mi := &file_SiLAService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServerName_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServerName_Responses) ProtoMessage() {}

func (x *SetServerName_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServerName_Responses.ProtoReflect.Descriptor instead.
func (*SetServerName_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{3}
}

type Get_ServerName_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerName_Parameters) Reset() {
	*x = Get_ServerName_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerName_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerName_Parameters) ProtoMessage() {}

func (x *Get_ServerName_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerName_Parameters.ProtoReflect.Descriptor instead.
func (*Get_ServerName_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{4}
}

type Get_ServerName_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    *String                `protobuf:"bytes,1,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerName_Responses) Reset() {
	*x = Get_ServerName_Responses{}
	mi := &file_SiLAService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerName_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerName_Responses) ProtoMessage() {}

func (x *Get_ServerName_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerName_Responses.ProtoReflect.Descriptor instead.
func (*Get_ServerName_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{5}
}

func (x *Get_ServerName_Responses) GetServerName() *String {
	if x != nil {
		return x.ServerName
	}
	return nil
}

type Get_ServerType_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerType_Parameters) Reset() {
	*x = Get_ServerType_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerType_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerType_Parameters) ProtoMessage() {}

func (x *Get_ServerType_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerType_Parameters.ProtoReflect.Descriptor instead.
func (*Get_ServerType_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{6}
}

type Get_ServerType_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerType    *String                `protobuf:"bytes,1,opt,name=ServerType,proto3" json:"ServerType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerType_Responses) Reset() {
	*x = Get_ServerType_Responses{}
	mi := &file_SiLAService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerType_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerType_Responses) ProtoMessage() {}

func (x *Get_ServerType_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerType_Responses.ProtoReflect.Descriptor instead.
func (*Get_ServerType_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{7}
}

func (x *Get_ServerType_Responses) GetServerType() *String {
	if x != nil {
		return x.ServerType
	}
	return nil
}

type Get_ServerUUID_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerUUID_Parameters) Reset() {
	*x = Get_ServerUUID_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerUUID_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerUUID_Parameters) ProtoMessage() {}

func (x *Get_ServerUUID_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerUUID_Parameters.ProtoReflect.Descriptor instead.
func (*Get_ServerUUID_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{8}
}

type Get_ServerUUID_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUUID    *String                `protobuf:"bytes,1,opt,name=ServerUUID,proto3" json:"ServerUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerUUID_Responses) Reset() {
	*x = Get_ServerUUID_Responses{}
	mi := &file_SiLAService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerUUID_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerUUID_Responses) ProtoMessage() {}

func (x *Get_ServerUUID_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerUUID_Responses.ProtoReflect.Descriptor instead.
func (*Get_ServerUUID_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{9}
}

func (x *Get_ServerUUID_Responses) GetServerUUID() *String {
	if x != nil {
		return x.ServerUUID
	}
	return nil
}

type Get_ServerDescription_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerDescription_Parameters) Reset() {
	*x = Get_ServerDescription_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerDescription_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerDescription_Parameters) ProtoMessage() {}

func (x *Get_ServerDescription_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerDescription_Parameters.ProtoReflect.Descriptor instead.
func (*Get_ServerDescription_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{10}
}

type Get_ServerDescription_Responses struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerDescription *String                `protobuf:"bytes,1,opt,name=ServerDescription,proto3" json:"ServerDescription,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Get_ServerDescription_Responses) Reset() {
	*x = Get_ServerDescription_Responses{}
	mi := &file_SiLAService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerDescription_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerDescription_Responses) ProtoMessage() {}

func (x *Get_ServerDescription_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerDescription_Responses.ProtoReflect.Descriptor instead.
func (*Get_ServerDescription_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{11}
}

func (x *Get_ServerDescription_Responses) GetServerDescription() *String {
	if x != nil {
		return x.ServerDescription
	}
	return nil
}

type Get_ServerVersion_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerVersion_Parameters) Reset() {
	*x = Get_ServerVersion_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerVersion_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerVersion_Parameters) ProtoMessage() {}

func (x *Get_ServerVersion_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerVersion_Parameters.ProtoReflect.Descriptor instead.
func (*Get_ServerVersion_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{12}
}

type Get_ServerVersion_Responses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion *String                `protobuf:"bytes,1,opt,name=ServerVersion,proto3" json:"ServerVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerVersion_Responses) Reset() {
	*x = Get_ServerVersion_Responses{}
	mi := &file_SiLAService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerVersion_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerVersion_Responses) ProtoMessage() {}

func (x *Get_ServerVersion_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerVersion_Responses.ProtoReflect.Descriptor instead.
func (*Get_ServerVersion_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{13}
}

func (x *Get_ServerVersion_Responses) GetServerVersion() *String {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

type Get_ServerVendorURL_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ServerVendorURL_Parameters) Reset() {
	*x = Get_ServerVendorURL_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerVendorURL_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerVendorURL_Parameters) ProtoMessage() {}

func (x *Get_ServerVendorURL_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerVendorURL_Parameters.ProtoReflect.Descriptor instead.
func (*Get_ServerVendorURL_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{14}
}

type Get_ServerVendorURL_Responses struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerVendorURL *String                `protobuf:"bytes,1,opt,name=ServerVendorURL,proto3" json:"ServerVendorURL,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Get_ServerVendorURL_Responses) Reset() {
	*x = Get_ServerVendorURL_Responses{}
	mi := &file_SiLAService_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ServerVendorURL_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ServerVendorURL_Responses) ProtoMessage() {}

func (x *Get_ServerVendorURL_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ServerVendorURL_Responses.ProtoReflect.Descriptor instead.
func (*Get_ServerVendorURL_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{15}
}

func (x *Get_ServerVendorURL_Responses) GetServerVendorURL() *String {
	if x != nil {
		return x.ServerVendorURL
	}
	return nil
}

type Get_ImplementedFeatures_Parameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_ImplementedFeatures_Parameters) Reset() {
	*x = Get_ImplementedFeatures_Parameters{}
	mi := &file_SiLAService_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ImplementedFeatures_Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ImplementedFeatures_Parameters) ProtoMessage() {}

func (x *Get_ImplementedFeatures_Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ImplementedFeatures_Parameters.ProtoReflect.Descriptor instead.
func (*Get_ImplementedFeatures_Parameters) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{16}
}

type Get_ImplementedFeatures_Responses struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ImplementedFeatures []*String              `protobuf:"bytes,1,rep,name=ImplementedFeatures,proto3" json:"ImplementedFeatures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Get_ImplementedFeatures_Responses) Reset() {
	*x = Get_ImplementedFeatures_Responses{}
	mi := &file_SiLAService_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_ImplementedFeatures_Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_ImplementedFeatures_Responses) ProtoMessage() {}

func (x *Get_ImplementedFeatures_Responses) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAService_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_ImplementedFeatures_Responses.ProtoReflect.Descriptor instead.
func (*Get_ImplementedFeatures_Responses) Descriptor() ([]byte, []int) {
	return file_SiLAService_proto_rawDescGZIP(), []int{17}
}

func (x *Get_ImplementedFeatures_Responses) GetImplementedFeatures() []*String {
	if x != nil {
		return x.ImplementedFeatures
	}
	return nil
}

var File_SiLAService_proto protoreflect.FileDescriptor

const file_SiLAService_proto_rawDesc = "" +
	"\n" +
	"\x11SiLAService.proto\x12*sila2.org.silastandard.core.silaservice.v1\x1a\x13SiLAFramework.proto\"o\n" +
	"\x1fGetFeatureDefinition_Parameters\x12L\n" +
	"\x11FeatureIdentifier\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\x11FeatureIdentifier\"n\n" +
	"\x1eGetFeatureDefinition_Responses\x12L\n" +
	"\x11FeatureDefinition\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\x11FeatureDefinition\"Z\n" +
	"\x18SetServerName_Parameters\x12>\n" +
	"\n" +
	"ServerName\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\n" +
	"ServerName\"\x19\n" +
	"\x17SetServerName_Responses\"\x1b\n" +
	"\x19Get_ServerName_Parameters\"Z\n" +
	"\x18Get_ServerName_Responses\x12>\n" +
	"\n" +
	"ServerName\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\n" +
	"ServerName\"\x1b\n" +
	"\x19Get_ServerType_Parameters\"Z\n" +
	"\x18Get_ServerType_Responses\x12>\n" +
	"\n" +
	"ServerType\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\n" +
	"ServerType\"\x1b\n" +
	"\x19Get_ServerUUID_Parameters\"Z\n" +
	"\x18Get_ServerUUID_Responses\x12>\n" +
	"\n" +
	"ServerUUID\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\n" +
	"ServerUUID\"\"\n" +
	" Get_ServerDescription_Parameters\"o\n" +
	"\x1fGet_ServerDescription_Responses\x12L\n" +
	"\x11ServerDescription\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\x11ServerDescription\"\x1e\n" +
	"\x1cGet_ServerVersion_Parameters\"c\n" +
	"\x1bGet_ServerVersion_Responses\x12D\n" +
	"\rServerVersion\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\rServerVersion\" \n" +
	"\x1eGet_ServerVendorURL_Parameters\"i\n" +
	"\x1dGet_ServerVendorURL_Responses\x12H\n" +
	"\x0fServerVendorURL\x18\x01 \x01(\v2\x1e.sila2.org.silastandard.StringR\x0fServerVendorURL\"$\n" +
	"\"Get_ImplementedFeatures_Parameters\"u\n" +
	"!Get_ImplementedFeatures_Responses\x12P\n" +
	"\x13ImplementedFeatures\x18\x01 \x03(\v2\x1e.sila2.org.silastandard.StringR\x13ImplementedFeatures2\x96\f\n" +
	"\vSiLAService\x12\xb1\x01\n" +
	"\x14GetFeatureDefinition\x12K.sila2.org.silastandard.core.silaservice.v1.GetFeatureDefinition_Parameters\x1aJ.sila2.org.silastandard.core.silaservice.v1.GetFeatureDefinition_Responses\"\x00\x12\x9c\x01\n" +
	"\rSetServerName\x12D.sila2.org.silastandard.core.silaservice.v1.SetServerName_Parameters\x1aC.sila2.org.silastandard.core.silaservice.v1.SetServerName_Responses\"\x00\x12\x9f\x01\n" +
	"\x0eGet_ServerName\x12E.sila2.org.silastandard.core.silaservice.v1.Get_ServerName_Parameters\x1aD.sila2.org.silastandard.core.silaservice.v1.Get_ServerName_Responses\"\x00\x12\x9f\x01\n" +
	"\x0eGet_ServerType\x12E.sila2.org.silastandard.core.silaservice.v1.Get_ServerType_Parameters\x1aD.sila2.org.silastandard.core.silaservice.v1.Get_ServerType_Responses\"\x00\x12\x9f\x01\n" +
	"\x0eGet_ServerUUID\x12E.sila2.org.silastandard.core.silaservice.v1.Get_ServerUUID_Parameters\x1aD.sila2.org.silastandard.core.silaservice.v1.Get_ServerUUID_Responses\"\x00\x12\xb4\x01\n" +
	"\x15Get_ServerDescription\x12L.sila2.org.silastandard.core.silaservice.v1.Get_ServerDescription_Parameters\x1aK.sila2.org.silastandard.core.silaservice.v1.Get_ServerDescription_Responses\"\x00\x12\xa8\x01\n" +
	"\x11Get_ServerVersion\x12H.sila2.org.silastandard.core.silaservice.v1.Get_ServerVersion_Parameters\x1aG.sila2.org.silastandard.core.silaservice.v1.Get_ServerVersion_Responses\"\x00\x12\xae\x01\n" +
	"\x13Get_ServerVendorURL\x12J.sila2.org.silastandard.core.silaservice.v1.Get_ServerVendorURL_Parameters\x1aI.sila2.org.silastandard.core.silaservice.v1.Get_ServerVendorURL_Responses\"\x00\x12\xba\x01\n" +
	"\x17Get_ImplementedFeatures\x12N.sila2.org.silastandard.core.silaservice.v1.Get_ImplementedFeatures_Parameters\x1aM.sila2.org.silastandard.core.silaservice.v1.Get_ImplementedFeatures_Responses\"\x00B6Z4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_SiLAService_proto_rawDescOnce sync.Once
	file_SiLAService_proto_rawDescData []byte
)

func file_SiLAService_proto_rawDescGZIP() []byte {
	file_SiLAService_proto_rawDescOnce.Do(func() {
		file_SiLAService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SiLAService_proto_rawDesc), len(file_SiLAService_proto_rawDesc)))
	})
	return file_SiLAService_proto_rawDescData
}

var file_SiLAService_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_SiLAService_proto_goTypes = []any{
	(*GetFeatureDefinition_Parameters)(nil),    // 0: sila2.org.silastandard.core.silaservice.v1.GetFeatureDefinition_Parameters
	(*GetFeatureDefinition_Responses)(nil),     // 1: sila2.org.silastandard.core.silaservice.v1.GetFeatureDefinition_Responses
	(*SetServerName_Parameters)(nil),           // 2: sila2.org.silastandard.core.silaservice.v1.SetServerName_Parameters
	(*SetServerName_Responses)(nil),            // 3: sila2.org.silastandard.core.silaservice.v1.SetServerName_Responses
	(*Get_ServerName_Parameters)(nil),          // 4: sila2.org.silastandard.core.silaservice.v1.Get_ServerName_Parameters
	(*Get_ServerName_Responses)(nil),           // 5: sila2.org.silastandard.core.silaservice.v1.Get_ServerName_Responses
	(*Get_ServerType_Parameters)(nil),          // 6: sila2.org.silastandard.core.silaservice.v1.Get_ServerType_Parameters
	(*Get_ServerType_Responses)(nil),           // 7: sila2.org.silastandard.core.silaservice.v1.Get_ServerType_Responses
	(*Get_ServerUUID_Parameters)(nil),          // 8: sila2.org.silastandard.core.silaservice.v1.Get_ServerUUID_Parameters
	(*Get_ServerUUID_Responses)(nil),           // 9: sila2.org.silastandard.core.silaservice.v1.Get_ServerUUID_Responses
	(*Get_ServerDescription_Parameters)(nil),   // 10: sila2.org.silastandard.core.silaservice.v1.Get_ServerDescription_Parameters
	(*Get_ServerDescription_Responses)(nil),    // 11: sila2.org.silastandard.core.silaservice.v1.Get_ServerDescription_Responses
	(*Get_ServerVersion_Parameters)(nil),       // 12: sila2.org.silastandard.core.silaservice.v1.Get_ServerVersion_Parameters
	(*Get_ServerVersion_Responses)(nil),        // 13: sila2.org.silastandard.core.silaservice.v1.Get_ServerVersion_Responses
	(*Get_ServerVendorURL_Parameters)(nil),     // 14: sila2.org.silastandard.core.silaservice.v1.Get_ServerVendorURL_Parameters
	(*Get_ServerVendorURL_Responses)(nil),      // 15: sila2.org.silastandard.core.silaservice.v1.Get_ServerVendorURL_Responses
	(*Get_ImplementedFeatures_Parameters)(nil), // 16: sila2.org.silastandard.core.silaservice.v1.Get_ImplementedFeatures_Parameters
	(*Get_ImplementedFeatures_Responses)(nil),  // 17: sila2.org.silastandard.core.silaservice.v1.Get_ImplementedFeatures_Responses
	(*String)(nil), // 18: sila2.org.silastandard.String
}
var file_SiLAService_proto_depIdxs = []int32{
	18, // 0: sila2.org.silastandard.core.silaservice.v1.GetFeatureDefinition_Parameters.FeatureIdentifier:type_name -> sila2.org.silastandard.String
	18, // 1: sila2.org.silastandard.core.silaservice.v1.GetFeatureDefinition_Responses.FeatureDefinition:type_name -> sila2.org.silastandard.String
	18, // 2: sila2.org.silastandard.core.silaservice.v1.SetServerName_Parameters.ServerName:type_name -> sila2.org.silastandard.String
	18, // 3: sila2.org.silastandard.core.silaservice.v1.Get_ServerName_Responses.ServerName:type_name -> sila2.org.silastandard.String
	18, // 4: sila2.org.silastandard.core.silaservice.v1.Get_ServerType_Responses.ServerType:type_name -> sila2.org.silastandard.String
	18, // 5: sila2.org.silastandard.core.silaservice.v1.Get_ServerUUID_Responses.ServerUUID:type_name -> sila2.org.silastandard.String
	18, // 6: sila2.org.silastandard.core.silaservice.v1.Get_ServerDescription_Responses.ServerDescription:type_name -> sila2.org.silastandard.String
	18, // 7: sila2.org.silastandard.core.silaservice.v1.Get_ServerVersion_Responses.ServerVersion:type_name -> sila2.org.silastandard.String
	18, // 8: sila2.org.silastandard.core.silaservice.v1.Get_ServerVendorURL_Responses.ServerVendorURL:type_name -> sila2.org.silastandard.String
	18, // 9: sila2.org.silastandard.core.silaservice.v1.Get_ImplementedFeatures_Responses.ImplementedFeatures:type_name -> sila2.org.silastandard.String
	0,  // 10: sila2.org.silastandard.core.silaservice.v1.SiLAService.GetFeatureDefinition:input_type -> sila2.org.silastandard.core.silaservice.v1.GetFeatureDefinition_Parameters
	2,  // 11: sila2.org.silastandard.core.silaservice.v1.SiLAService.SetServerName:input_type -> sila2.org.silastandard.core.silaservice.v1.SetServerName_Parameters
	4,  // 12: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerName:input_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerName_Parameters
	6,  // 13: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerType:input_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerType_Parameters
	8,  // 14: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerUUID:input_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerUUID_Parameters
	10, // 15: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerDescription:input_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerDescription_Parameters
	12, // 16: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerVersion:input_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerVersion_Parameters
	14, // 17: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerVendorURL:input_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerVendorURL_Parameters
	16, // 18: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ImplementedFeatures:input_type -> sila2.org.silastandard.core.silaservice.v1.Get_ImplementedFeatures_Parameters
	1,  // 19: sila2.org.silastandard.core.silaservice.v1.SiLAService.GetFeatureDefinition:output_type -> sila2.org.silastandard.core.silaservice.v1.GetFeatureDefinition_Responses
	3,  // 20: sila2.org.silastandard.core.silaservice.v1.SiLAService.SetServerName:output_type -> sila2.org.silastandard.core.silaservice.v1.SetServerName_Responses
	5,  // 21: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerName:output_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerName_Responses
	7,  // 22: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerType:output_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerType_Responses
	9,  // 23: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerUUID:output_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerUUID_Responses
	11, // 24: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerDescription:output_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerDescription_Responses
	13, // 25: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerVersion:output_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerVersion_Responses
	15, // 26: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ServerVendorURL:output_type -> sila2.org.silastandard.core.silaservice.v1.Get_ServerVendorURL_Responses
	17, // 27: sila2.org.silastandard.core.silaservice.v1.SiLAService.Get_ImplementedFeatures:output_type -> sila2.org.silastandard.core.silaservice.v1.Get_ImplementedFeatures_Responses
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_SiLAService_proto_init() }
func file_SiLAService_proto_init() {
	if File_SiLAService_proto != nil {
		return
	}
	file_SiLAFramework_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SiLAService_proto_rawDesc), len(file_SiLAService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SiLAService_proto_goTypes,
		DependencyIndexes: file_SiLAService_proto_depIdxs,
		MessageInfos:      file_SiLAService_proto_msgTypes,
	}.Build()
	File_SiLAService_proto = out.File
	file_SiLAService_proto_goTypes = nil
	file_SiLAService_proto_depIdxs = nil
}
