// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: SiLAService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SiLAService_GetFeatureDefinition_FullMethodName    = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/GetFeatureDefinition"
	SiLAService_SetServerName_FullMethodName           = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/SetServerName"
	SiLAService_Get_ServerName_FullMethodName          = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/Get_ServerName"
	SiLAService_Get_ServerType_FullMethodName          = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/Get_ServerType"
	SiLAService_Get_ServerUUID_FullMethodName          = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/Get_ServerUUID"
	SiLAService_Get_ServerDescription_FullMethodName   = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/Get_ServerDescription"
	SiLAService_Get_ServerVersion_FullMethodName       = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/Get_ServerVersion"
	SiLAService_Get_ServerVendorURL_FullMethodName     = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/Get_ServerVendorURL"
	SiLAService_Get_ImplementedFeatures_FullMethodName = "/sila2.org.silastandard.core.silaservice.v1.SiLAService/Get_ImplementedFeatures"
)

// SiLAServiceClient is the client API for SiLAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SiLAServiceClient interface {
	// ---- Commands ----
	GetFeatureDefinition(ctx context.Context, in *GetFeatureDefinition_Parameters, opts ...grpc.CallOption) (*GetFeatureDefinition_Responses, error)
	SetServerName(ctx context.Context, in *SetServerName_Parameters, opts ...grpc.CallOption) (*SetServerName_Responses, error)
	// ---- Property getters ----
	Get_ServerName(ctx context.Context, in *Get_ServerName_Parameters, opts ...grpc.CallOption) (*Get_ServerName_Responses, error)
	Get_ServerType(ctx context.Context, in *Get_ServerType_Parameters, opts ...grpc.CallOption) (*Get_ServerType_Responses, error)
	Get_ServerUUID(ctx context.Context, in *Get_ServerUUID_Parameters, opts ...grpc.CallOption) (*Get_ServerUUID_Responses, error)
	Get_ServerDescription(ctx context.Context, in *Get_ServerDescription_Parameters, opts ...grpc.CallOption) (*Get_ServerDescription_Responses, error)
	Get_ServerVersion(ctx context.Context, in *Get_ServerVersion_Parameters, opts ...grpc.CallOption) (*Get_ServerVersion_Responses, error)
	Get_ServerVendorURL(ctx context.Context, in *Get_ServerVendorURL_Parameters, opts ...grpc.CallOption) (*Get_ServerVendorURL_Responses, error)
	Get_ImplementedFeatures(ctx context.Context, in *Get_ImplementedFeatures_Parameters, opts ...grpc.CallOption) (*Get_ImplementedFeatures_Responses, error)
}

type siLAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSiLAServiceClient(cc grpc.ClientConnInterface) SiLAServiceClient {
	return &siLAServiceClient{cc}
}

func (c *siLAServiceClient) GetFeatureDefinition(ctx context.Context, in *GetFeatureDefinition_Parameters, opts ...grpc.CallOption) (*GetFeatureDefinition_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeatureDefinition_Responses)
	err := c.cc.Invoke(ctx, SiLAService_GetFeatureDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siLAServiceClient) SetServerName(ctx context.Context, in *SetServerName_Parameters, opts ...grpc.CallOption) (*SetServerName_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServerName_Responses)
	err := c.cc.Invoke(ctx, SiLAService_SetServerName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siLAServiceClient) Get_ServerName(ctx context.Context, in *Get_ServerName_Parameters, opts ...grpc.CallOption) (*Get_ServerName_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_ServerName_Responses)
	err := c.cc.Invoke(ctx, SiLAService_Get_ServerName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siLAServiceClient) Get_ServerType(ctx context.Context, in *Get_ServerType_Parameters, opts ...grpc.CallOption) (*Get_ServerType_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_ServerType_Responses)
	err := c.cc.Invoke(ctx, SiLAService_Get_ServerType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siLAServiceClient) Get_ServerUUID(ctx context.Context, in *Get_ServerUUID_Parameters, opts ...grpc.CallOption) (*Get_ServerUUID_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_ServerUUID_Responses)
	err := c.cc.Invoke(ctx, SiLAService_Get_ServerUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siLAServiceClient) Get_ServerDescription(ctx context.Context, in *Get_ServerDescription_Parameters, opts ...grpc.CallOption) (*Get_ServerDescription_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_ServerDescription_Responses)
	err := c.cc.Invoke(ctx, SiLAService_Get_ServerDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siLAServiceClient) Get_ServerVersion(ctx context.Context, in *Get_ServerVersion_Parameters, opts ...grpc.CallOption) (*Get_ServerVersion_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_ServerVersion_Responses)
	err := c.cc.Invoke(ctx, SiLAService_Get_ServerVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siLAServiceClient) Get_ServerVendorURL(ctx context.Context, in *Get_ServerVendorURL_Parameters, opts ...grpc.CallOption) (*Get_ServerVendorURL_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_ServerVendorURL_Responses)
	err := c.cc.Invoke(ctx, SiLAService_Get_ServerVendorURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siLAServiceClient) Get_ImplementedFeatures(ctx context.Context, in *Get_ImplementedFeatures_Parameters, opts ...grpc.CallOption) (*Get_ImplementedFeatures_Responses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_ImplementedFeatures_Responses)
	err := c.cc.Invoke(ctx, SiLAService_Get_ImplementedFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiLAServiceServer is the server API for SiLAService service.
// All implementations must embed UnimplementedSiLAServiceServer
// for forward compatibility.
type SiLAServiceServer interface {
	// ---- Commands ----
	GetFeatureDefinition(context.Context, *GetFeatureDefinition_Parameters) (*GetFeatureDefinition_Responses, error)
	SetServerName(context.Context, *SetServerName_Parameters) (*SetServerName_Responses, error)
	// ---- Property getters ----
	Get_ServerName(context.Context, *Get_ServerName_Parameters) (*Get_ServerName_Responses, error)
	Get_ServerType(context.Context, *Get_ServerType_Parameters) (*Get_ServerType_Responses, error)
	Get_ServerUUID(context.Context, *Get_ServerUUID_Parameters) (*Get_ServerUUID_Responses, error)
	Get_ServerDescription(context.Context, *Get_ServerDescription_Parameters) (*Get_ServerDescription_Responses, error)
	Get_ServerVersion(context.Context, *Get_ServerVersion_Parameters) (*Get_ServerVersion_Responses, error)
	Get_ServerVendorURL(context.Context, *Get_ServerVendorURL_Parameters) (*Get_ServerVendorURL_Responses, error)
	Get_ImplementedFeatures(context.Context, *Get_ImplementedFeatures_Parameters) (*Get_ImplementedFeatures_Responses, error)
	mustEmbedUnimplementedSiLAServiceServer()
}

// UnimplementedSiLAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSiLAServiceServer struct{}

func (UnimplementedSiLAServiceServer) GetFeatureDefinition(context.Context, *GetFeatureDefinition_Parameters) (*GetFeatureDefinition_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeatureDefinition not implemented")
}
func (UnimplementedSiLAServiceServer) SetServerName(context.Context, *SetServerName_Parameters) (*SetServerName_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method SetServerName not implemented")
}
func (UnimplementedSiLAServiceServer) Get_ServerName(context.Context, *Get_ServerName_Parameters) (*Get_ServerName_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_ServerName not implemented")
}
func (UnimplementedSiLAServiceServer) Get_ServerType(context.Context, *Get_ServerType_Parameters) (*Get_ServerType_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_ServerType not implemented")
}
func (UnimplementedSiLAServiceServer) Get_ServerUUID(context.Context, *Get_ServerUUID_Parameters) (*Get_ServerUUID_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_ServerUUID not implemented")
}
func (UnimplementedSiLAServiceServer) Get_ServerDescription(context.Context, *Get_ServerDescription_Parameters) (*Get_ServerDescription_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_ServerDescription not implemented")
}
func (UnimplementedSiLAServiceServer) Get_ServerVersion(context.Context, *Get_ServerVersion_Parameters) (*Get_ServerVersion_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_ServerVersion not implemented")
}
func (UnimplementedSiLAServiceServer) Get_ServerVendorURL(context.Context, *Get_ServerVendorURL_Parameters) (*Get_ServerVendorURL_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_ServerVendorURL not implemented")
}
func (UnimplementedSiLAServiceServer) Get_ImplementedFeatures(context.Context, *Get_ImplementedFeatures_Parameters) (*Get_ImplementedFeatures_Responses, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_ImplementedFeatures not implemented")
}
func (UnimplementedSiLAServiceServer) mustEmbedUnimplementedSiLAServiceServer() {}
func (UnimplementedSiLAServiceServer) testEmbeddedByValue()                     {}

// UnsafeSiLAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SiLAServiceServer will
// result in compilation errors.
type UnsafeSiLAServiceServer interface {
	mustEmbedUnimplementedSiLAServiceServer()
}

func RegisterSiLAServiceServer(s grpc.ServiceRegistrar, srv SiLAServiceServer) {
	// If the following call panics, it indicates UnimplementedSiLAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SiLAService_ServiceDesc, srv)
}

func _SiLAService_GetFeatureDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeatureDefinition_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).GetFeatureDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_GetFeatureDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).GetFeatureDefinition(ctx, req.(*GetFeatureDefinition_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiLAService_SetServerName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServerName_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).SetServerName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_SetServerName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).SetServerName(ctx, req.(*SetServerName_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiLAService_Get_ServerName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_ServerName_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).Get_ServerName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_Get_ServerName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).Get_ServerName(ctx, req.(*Get_ServerName_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiLAService_Get_ServerType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_ServerType_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).Get_ServerType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_Get_ServerType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).Get_ServerType(ctx, req.(*Get_ServerType_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiLAService_Get_ServerUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_ServerUUID_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).Get_ServerUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_Get_ServerUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).Get_ServerUUID(ctx, req.(*Get_ServerUUID_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiLAService_Get_ServerDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_ServerDescription_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).Get_ServerDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_Get_ServerDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).Get_ServerDescription(ctx, req.(*Get_ServerDescription_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiLAService_Get_ServerVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_ServerVersion_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).Get_ServerVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_Get_ServerVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).Get_ServerVersion(ctx, req.(*Get_ServerVersion_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiLAService_Get_ServerVendorURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_ServerVendorURL_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).Get_ServerVendorURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_Get_ServerVendorURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).Get_ServerVendorURL(ctx, req.(*Get_ServerVendorURL_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiLAService_Get_ImplementedFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get_ImplementedFeatures_Parameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiLAServiceServer).Get_ImplementedFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiLAService_Get_ImplementedFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiLAServiceServer).Get_ImplementedFeatures(ctx, req.(*Get_ImplementedFeatures_Parameters))
	}
	return interceptor(ctx, in, info, handler)
}

// SiLAService_ServiceDesc is the grpc.ServiceDesc for SiLAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SiLAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sila2.org.silastandard.core.silaservice.v1.SiLAService",
	HandlerType: (*SiLAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeatureDefinition",
			Handler:    _SiLAService_GetFeatureDefinition_Handler,
		},
		{
			MethodName: "SetServerName",
			Handler:    _SiLAService_SetServerName_Handler,
		},
		{
			MethodName: "Get_ServerName",
			Handler:    _SiLAService_Get_ServerName_Handler,
		},
		{
			MethodName: "Get_ServerType",
			Handler:    _SiLAService_Get_ServerType_Handler,
		},
		{
			MethodName: "Get_ServerUUID",
			Handler:    _SiLAService_Get_ServerUUID_Handler,
		},
		{
			MethodName: "Get_ServerDescription",
			Handler:    _SiLAService_Get_ServerDescription_Handler,
		},
		{
			MethodName: "Get_ServerVersion",
			Handler:    _SiLAService_Get_ServerVersion_Handler,
		},
		{
			MethodName: "Get_ServerVendorURL",
			Handler:    _SiLAService_Get_ServerVendorURL_Handler,
		},
		{
			MethodName: "Get_ImplementedFeatures",
			Handler:    _SiLAService_Get_ImplementedFeatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SiLAService.proto",
}
