// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: SiLAFramework.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionInfo_CommandStatus int32

const (
	ExecutionInfo_waiting              ExecutionInfo_CommandStatus = 0
	ExecutionInfo_running              ExecutionInfo_CommandStatus = 1
	ExecutionInfo_finishedSuccessfully ExecutionInfo_CommandStatus = 2
	ExecutionInfo_finishedWithError    ExecutionInfo_CommandStatus = 3
)

// Enum value maps for ExecutionInfo_CommandStatus.
var (
	ExecutionInfo_CommandStatus_name = map[int32]string{
		0: "waiting",
		1: "running",
		2: "finishedSuccessfully",
		3: "finishedWithError",
	}
	ExecutionInfo_CommandStatus_value = map[string]int32{
		"waiting":              0,
		"running":              1,
		"finishedSuccessfully": 2,
		"finishedWithError":    3,
	}
)

func (x ExecutionInfo_CommandStatus) Enum() *ExecutionInfo_CommandStatus {
	p := new(ExecutionInfo_CommandStatus)
	*p = x
	return p
}

func (x ExecutionInfo_CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionInfo_CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_SiLAFramework_proto_enumTypes[0].Descriptor()
}

func (ExecutionInfo_CommandStatus) Type() protoreflect.EnumType {
	return &file_SiLAFramework_proto_enumTypes[0]
}

func (x ExecutionInfo_CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionInfo_CommandStatus.Descriptor instead.
func (ExecutionInfo_CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{11, 0}
}

type FrameworkError_ErrorType int32

const (
	FrameworkError_COMMAND_EXECUTION_NOT_ACCEPTED FrameworkError_ErrorType = 0
	FrameworkError_INVALID_COMMAND_EXECUTION_UUID FrameworkError_ErrorType = 1
	FrameworkError_COMMAND_EXECUTION_NOT_FINISHED FrameworkError_ErrorType = 2
	FrameworkError_INVALID_METADATA               FrameworkError_ErrorType = 3
	FrameworkError_NO_METADATA_ALLOWED            FrameworkError_ErrorType = 4
)

// Enum value maps for FrameworkError_ErrorType.
var (
	FrameworkError_ErrorType_name = map[int32]string{
		0: "COMMAND_EXECUTION_NOT_ACCEPTED",
		1: "INVALID_COMMAND_EXECUTION_UUID",
		2: "COMMAND_EXECUTION_NOT_FINISHED",
		3: "INVALID_METADATA",
		4: "NO_METADATA_ALLOWED",
	}
	FrameworkError_ErrorType_value = map[string]int32{
		"COMMAND_EXECUTION_NOT_ACCEPTED": 0,
		"INVALID_COMMAND_EXECUTION_UUID": 1,
		"COMMAND_EXECUTION_NOT_FINISHED": 2,
		"INVALID_METADATA":               3,
		"NO_METADATA_ALLOWED":            4,
	}
)

func (x FrameworkError_ErrorType) Enum() *FrameworkError_ErrorType {
	p := new(FrameworkError_ErrorType)
	*p = x
	return p
}

func (x FrameworkError_ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameworkError_ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_SiLAFramework_proto_enumTypes[1].Descriptor()
}

func (FrameworkError_ErrorType) Type() protoreflect.EnumType {
	return &file_SiLAFramework_proto_enumTypes[1]
}

func (x FrameworkError_ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameworkError_ErrorType.Descriptor instead.
func (FrameworkError_ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{16, 0}
}

// -------- SiLA Basic Types --------
type String struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *String) Reset() {
	*x = String{}
	mi := &file_SiLAFramework_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{0}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Integer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integer) Reset() {
	*x = Integer{}
	mi := &file_SiLAFramework_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integer) ProtoMessage() {}

func (x *Integer) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integer.ProtoReflect.Descriptor instead.
func (*Integer) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{1}
}

func (x *Integer) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Real struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Real) Reset() {
	*x = Real{}
	mi := &file_SiLAFramework_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Real) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Real) ProtoMessage() {}

func (x *Real) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Real.ProtoReflect.Descriptor instead.
func (*Real) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{2}
}

func (x *Real) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Boolean struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Boolean) Reset() {
	*x = Boolean{}
	mi := &file_SiLAFramework_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Boolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boolean) ProtoMessage() {}

func (x *Boolean) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boolean.ProtoReflect.Descriptor instead.
func (*Boolean) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{3}
}

func (x *Boolean) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type Binary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Union:
	//
	//	*Binary_Value
	//	*Binary_BinaryTransferUUID
	Union         isBinary_Union `protobuf_oneof:"union"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_SiLAFramework_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{4}
}

func (x *Binary) GetUnion() isBinary_Union {
	if x != nil {
		return x.Union
	}
	return nil
}

func (x *Binary) GetValue() []byte {
	if x != nil {
		if x, ok := x.Union.(*Binary_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Binary) GetBinaryTransferUUID() string {
	if x != nil {
		if x, ok := x.Union.(*Binary_BinaryTransferUUID); ok {
			return x.BinaryTransferUUID
		}
	}
	return ""
}

type isBinary_Union interface {
	isBinary_Union()
}

type Binary_Value struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type Binary_BinaryTransferUUID struct {
	BinaryTransferUUID string `protobuf:"bytes,2,opt,name=binaryTransferUUID,proto3,oneof"`
}

func (*Binary_Value) isBinary_Union() {}

func (*Binary_BinaryTransferUUID) isBinary_Union() {}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           uint32                 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month         uint32                 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year          uint32                 `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Timezone      *Timezone              `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_SiLAFramework_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{5}
}

func (x *Date) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Date) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetTimezone() *Timezone {
	if x != nil {
		return x.Timezone
	}
	return nil
}

type Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Second        uint32                 `protobuf:"varint,1,opt,name=second,proto3" json:"second,omitempty"`
	Minute        uint32                 `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	Hour          uint32                 `protobuf:"varint,3,opt,name=hour,proto3" json:"hour,omitempty"`
	Timezone      *Timezone              `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Millisecond   uint32                 `protobuf:"varint,5,opt,name=millisecond,proto3" json:"millisecond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Time) Reset() {
	*x = Time{}
	mi := &file_SiLAFramework_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Time) ProtoMessage() {}

func (x *Time) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Time.ProtoReflect.Descriptor instead.
func (*Time) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{6}
}

func (x *Time) GetSecond() uint32 {
	if x != nil {
		return x.Second
	}
	return 0
}

func (x *Time) GetMinute() uint32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

func (x *Time) GetHour() uint32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *Time) GetTimezone() *Timezone {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *Time) GetMillisecond() uint32 {
	if x != nil {
		return x.Millisecond
	}
	return 0
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Second        uint32                 `protobuf:"varint,1,opt,name=second,proto3" json:"second,omitempty"`
	Minute        uint32                 `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	Hour          uint32                 `protobuf:"varint,3,opt,name=hour,proto3" json:"hour,omitempty"`
	Day           uint32                 `protobuf:"varint,4,opt,name=day,proto3" json:"day,omitempty"`
	Month         uint32                 `protobuf:"varint,5,opt,name=month,proto3" json:"month,omitempty"`
	Year          uint32                 `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	Timezone      *Timezone              `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Millisecond   uint32                 `protobuf:"varint,8,opt,name=millisecond,proto3" json:"millisecond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_SiLAFramework_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{7}
}

func (x *Timestamp) GetSecond() uint32 {
	if x != nil {
		return x.Second
	}
	return 0
}

func (x *Timestamp) GetMinute() uint32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

func (x *Timestamp) GetHour() uint32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *Timestamp) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Timestamp) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Timestamp) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Timestamp) GetTimezone() *Timezone {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *Timestamp) GetMillisecond() uint32 {
	if x != nil {
		return x.Millisecond
	}
	return 0
}

type Any struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Any) Reset() {
	*x = Any{}
	mi := &file_SiLAFramework_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Any) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Any) ProtoMessage() {}

func (x *Any) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Any.ProtoReflect.Descriptor instead.
func (*Any) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{8}
}

func (x *Any) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Any) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// -------- Framework Types --------
type CommandExecutionUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExecutionUUID) Reset() {
	*x = CommandExecutionUUID{}
	mi := &file_SiLAFramework_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecutionUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecutionUUID) ProtoMessage() {}

func (x *CommandExecutionUUID) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecutionUUID.ProtoReflect.Descriptor instead.
func (*CommandExecutionUUID) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{9}
}

func (x *CommandExecutionUUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CommandConfirmation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CommandExecutionUUID *CommandExecutionUUID  `protobuf:"bytes,1,opt,name=commandExecutionUUID,proto3" json:"commandExecutionUUID,omitempty"`
	LifetimeOfExecution  *Duration              `protobuf:"bytes,2,opt,name=lifetimeOfExecution,proto3" json:"lifetimeOfExecution,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CommandConfirmation) Reset() {
	*x = CommandConfirmation{}
	mi := &file_SiLAFramework_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandConfirmation) ProtoMessage() {}

func (x *CommandConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandConfirmation.ProtoReflect.Descriptor instead.
func (*CommandConfirmation) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{10}
}

func (x *CommandConfirmation) GetCommandExecutionUUID() *CommandExecutionUUID {
	if x != nil {
		return x.CommandExecutionUUID
	}
	return nil
}

func (x *CommandConfirmation) GetLifetimeOfExecution() *Duration {
	if x != nil {
		return x.LifetimeOfExecution
	}
	return nil
}

type ExecutionInfo struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	CommandStatus              ExecutionInfo_CommandStatus `protobuf:"varint,1,opt,name=commandStatus,proto3,enum=sila2.org.silastandard.ExecutionInfo_CommandStatus" json:"commandStatus,omitempty"`
	ProgressInfo               *Real                       `protobuf:"bytes,2,opt,name=progressInfo,proto3" json:"progressInfo,omitempty"`
	EstimatedRemainingTime     *Duration                   `protobuf:"bytes,3,opt,name=estimatedRemainingTime,proto3" json:"estimatedRemainingTime,omitempty"`
	UpdatedLifetimeOfExecution *Duration                   `protobuf:"bytes,4,opt,name=updatedLifetimeOfExecution,proto3" json:"updatedLifetimeOfExecution,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ExecutionInfo) Reset() {
	*x = ExecutionInfo{}
	mi := &file_SiLAFramework_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionInfo) ProtoMessage() {}

func (x *ExecutionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionInfo.ProtoReflect.Descriptor instead.
func (*ExecutionInfo) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutionInfo) GetCommandStatus() ExecutionInfo_CommandStatus {
	if x != nil {
		return x.CommandStatus
	}
	return ExecutionInfo_waiting
}

func (x *ExecutionInfo) GetProgressInfo() *Real {
	if x != nil {
		return x.ProgressInfo
	}
	return nil
}

func (x *ExecutionInfo) GetEstimatedRemainingTime() *Duration {
	if x != nil {
		return x.EstimatedRemainingTime
	}
	return nil
}

func (x *ExecutionInfo) GetUpdatedLifetimeOfExecution() *Duration {
	if x != nil {
		return x.UpdatedLifetimeOfExecution
	}
	return nil
}

// -------- Error Handling --------
type SiLAError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*SiLAError_ValidationError
	//	*SiLAError_DefinedExecutionError
	//	*SiLAError_UndefinedExecutionError
	//	*SiLAError_FrameworkError
	Error         isSiLAError_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiLAError) Reset() {
	*x = SiLAError{}
	mi := &file_SiLAFramework_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiLAError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiLAError) ProtoMessage() {}

func (x *SiLAError) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiLAError.ProtoReflect.Descriptor instead.
func (*SiLAError) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{12}
}

func (x *SiLAError) GetError() isSiLAError_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SiLAError) GetValidationError() *ValidationError {
	if x != nil {
		if x, ok := x.Error.(*SiLAError_ValidationError); ok {
			return x.ValidationError
		}
	}
	return nil
}

func (x *SiLAError) GetDefinedExecutionError() *DefinedExecutionError {
	if x != nil {
		if x, ok := x.Error.(*SiLAError_DefinedExecutionError); ok {
			return x.DefinedExecutionError
		}
	}
	return nil
}

func (x *SiLAError) GetUndefinedExecutionError() *UndefinedExecutionError {
	if x != nil {
		if x, ok := x.Error.(*SiLAError_UndefinedExecutionError); ok {
			return x.UndefinedExecutionError
		}
	}
	return nil
}

func (x *SiLAError) GetFrameworkError() *FrameworkError {
	if x != nil {
		if x, ok := x.Error.(*SiLAError_FrameworkError); ok {
			return x.FrameworkError
		}
	}
	return nil
}

type isSiLAError_Error interface {
	isSiLAError_Error()
}

type SiLAError_ValidationError struct {
	ValidationError *ValidationError `protobuf:"bytes,1,opt,name=validationError,proto3,oneof"`
}

type SiLAError_DefinedExecutionError struct {
	DefinedExecutionError *DefinedExecutionError `protobuf:"bytes,2,opt,name=definedExecutionError,proto3,oneof"`
}

type SiLAError_UndefinedExecutionError struct {
	UndefinedExecutionError *UndefinedExecutionError `protobuf:"bytes,3,opt,name=undefinedExecutionError,proto3,oneof"`
}

type SiLAError_FrameworkError struct {
	FrameworkError *FrameworkError `protobuf:"bytes,4,opt,name=frameworkError,proto3,oneof"`
}

func (*SiLAError_ValidationError) isSiLAError_Error() {}

func (*SiLAError_DefinedExecutionError) isSiLAError_Error() {}

func (*SiLAError_UndefinedExecutionError) isSiLAError_Error() {}

func (*SiLAError_FrameworkError) isSiLAError_Error() {}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameter     string                 `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"` // fully qualified parameter identifier
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_SiLAFramework_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{13}
}

func (x *ValidationError) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DefinedExecutionError struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ErrorIdentifier string                 `protobuf:"bytes,1,opt,name=errorIdentifier,proto3" json:"errorIdentifier,omitempty"` // fully qualified defined execution error identifier
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DefinedExecutionError) Reset() {
	*x = DefinedExecutionError{}
	mi := &file_SiLAFramework_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefinedExecutionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefinedExecutionError) ProtoMessage() {}

func (x *DefinedExecutionError) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefinedExecutionError.ProtoReflect.Descriptor instead.
func (*DefinedExecutionError) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{14}
}

func (x *DefinedExecutionError) GetErrorIdentifier() string {
	if x != nil {
		return x.ErrorIdentifier
	}
	return ""
}

func (x *DefinedExecutionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UndefinedExecutionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndefinedExecutionError) Reset() {
	*x = UndefinedExecutionError{}
	mi := &file_SiLAFramework_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndefinedExecutionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndefinedExecutionError) ProtoMessage() {}

func (x *UndefinedExecutionError) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndefinedExecutionError.ProtoReflect.Descriptor instead.
func (*UndefinedExecutionError) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{15}
}

func (x *UndefinedExecutionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FrameworkError struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ErrorType     FrameworkError_ErrorType `protobuf:"varint,1,opt,name=errorType,proto3,enum=sila2.org.silastandard.FrameworkError_ErrorType" json:"errorType,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameworkError) Reset() {
	*x = FrameworkError{}
	mi := &file_SiLAFramework_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameworkError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameworkError) ProtoMessage() {}

func (x *FrameworkError) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameworkError.ProtoReflect.Descriptor instead.
func (*FrameworkError) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{16}
}

func (x *FrameworkError) GetErrorType() FrameworkError_ErrorType {
	if x != nil {
		return x.ErrorType
	}
	return FrameworkError_COMMAND_EXECUTION_NOT_ACCEPTED
}

func (x *FrameworkError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// -------- Internal types --------
// Timezone: used in Date, Time, Timestamp
type Timezone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         int32                  `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes       uint32                 `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timezone) Reset() {
	*x = Timezone{}
	mi := &file_SiLAFramework_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timezone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timezone) ProtoMessage() {}

func (x *Timezone) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timezone.ProtoReflect.Descriptor instead.
func (*Timezone) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{17}
}

func (x *Timezone) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *Timezone) GetMinutes() uint32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

// Duration: used in CommandConfirmation, ExecutionInfo
type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_SiLAFramework_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_SiLAFramework_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_SiLAFramework_proto_rawDescGZIP(), []int{18}
}

func (x *Duration) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Duration) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_SiLAFramework_proto protoreflect.FileDescriptor

const file_SiLAFramework_proto_rawDesc = "" +
	"\n" +
	"\x13SiLAFramework.proto\x12\x16sila2.org.silastandard\"\x1e\n" +
	"\x06String\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1f\n" +
	"\aInteger\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"\x1c\n" +
	"\x04Real\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"\x1f\n" +
	"\aBoolean\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"[\n" +
	"\x06Binary\x12\x16\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x120\n" +
	"\x12binaryTransferUUID\x18\x02 \x01(\tH\x00R\x12binaryTransferUUIDB\a\n" +
	"\x05union\"\x80\x01\n" +
	"\x04Date\x12\x10\n" +
	"\x03day\x18\x01 \x01(\rR\x03day\x12\x14\n" +
	"\x05month\x18\x02 \x01(\rR\x05month\x12\x12\n" +
	"\x04year\x18\x03 \x01(\rR\x04year\x12<\n" +
	"\btimezone\x18\x04 \x01(\v2 .sila2.org.silastandard.TimezoneR\btimezone\"\xaa\x01\n" +
	"\x04Time\x12\x16\n" +
	"\x06second\x18\x01 \x01(\rR\x06second\x12\x16\n" +
	"\x06minute\x18\x02 \x01(\rR\x06minute\x12\x12\n" +
	"\x04hour\x18\x03 \x01(\rR\x04hour\x12<\n" +
	"\btimezone\x18\x04 \x01(\v2 .sila2.org.silastandard.TimezoneR\btimezone\x12 \n" +
	"\vmillisecond\x18\x05 \x01(\rR\vmillisecond\"\xeb\x01\n" +
	"\tTimestamp\x12\x16\n" +
	"\x06second\x18\x01 \x01(\rR\x06second\x12\x16\n" +
	"\x06minute\x18\x02 \x01(\rR\x06minute\x12\x12\n" +
	"\x04hour\x18\x03 \x01(\rR\x04hour\x12\x10\n" +
	"\x03day\x18\x04 \x01(\rR\x03day\x12\x14\n" +
	"\x05month\x18\x05 \x01(\rR\x05month\x12\x12\n" +
	"\x04year\x18\x06 \x01(\rR\x04year\x12<\n" +
	"\btimezone\x18\a \x01(\v2 .sila2.org.silastandard.TimezoneR\btimezone\x12 \n" +
	"\vmillisecond\x18\b \x01(\rR\vmillisecond\"3\n" +
	"\x03Any\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\",\n" +
	"\x14CommandExecutionUUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xcb\x01\n" +
	"\x13CommandConfirmation\x12`\n" +
	"\x14commandExecutionUUID\x18\x01 \x01(\v2,.sila2.org.silastandard.CommandExecutionUUIDR\x14commandExecutionUUID\x12R\n" +
	"\x13lifetimeOfExecution\x18\x02 \x01(\v2 .sila2.org.silastandard.DurationR\x13lifetimeOfExecution\"\xc4\x03\n" +
	"\rExecutionInfo\x12Y\n" +
	"\rcommandStatus\x18\x01 \x01(\x0e23.sila2.org.silastandard.ExecutionInfo.CommandStatusR\rcommandStatus\x12@\n" +
	"\fprogressInfo\x18\x02 \x01(\v2\x1c.sila2.org.silastandard.RealR\fprogressInfo\x12X\n" +
	"\x16estimatedRemainingTime\x18\x03 \x01(\v2 .sila2.org.silastandard.DurationR\x16estimatedRemainingTime\x12`\n" +
	"\x1aupdatedLifetimeOfExecution\x18\x04 \x01(\v2 .sila2.org.silastandard.DurationR\x1aupdatedLifetimeOfExecution\"Z\n" +
	"\rCommandStatus\x12\v\n" +
	"\awaiting\x10\x00\x12\v\n" +
	"\arunning\x10\x01\x12\x18\n" +
	"\x14finishedSuccessfully\x10\x02\x12\x15\n" +
	"\x11finishedWithError\x10\x03\"\x8f\x03\n" +
	"\tSiLAError\x12S\n" +
	"\x0fvalidationError\x18\x01 \x01(\v2'.sila2.org.silastandard.ValidationErrorH\x00R\x0fvalidationError\x12e\n" +
	"\x15definedExecutionError\x18\x02 \x01(\v2-.sila2.org.silastandard.DefinedExecutionErrorH\x00R\x15definedExecutionError\x12k\n" +
	"\x17undefinedExecutionError\x18\x03 \x01(\v2/.sila2.org.silastandard.UndefinedExecutionErrorH\x00R\x17undefinedExecutionError\x12P\n" +
	"\x0eframeworkError\x18\x04 \x01(\v2&.sila2.org.silastandard.FrameworkErrorH\x00R\x0eframeworkErrorB\a\n" +
	"\x05error\"I\n" +
	"\x0fValidationError\x12\x1c\n" +
	"\tparameter\x18\x01 \x01(\tR\tparameter\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x15DefinedExecutionError\x12(\n" +
	"\x0ferrorIdentifier\x18\x01 \x01(\tR\x0ferrorIdentifier\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x17UndefinedExecutionError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa3\x02\n" +
	"\x0eFrameworkError\x12N\n" +
	"\terrorType\x18\x01 \x01(\x0e20.sila2.org.silastandard.FrameworkError.ErrorTypeR\terrorType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\tErrorType\x12\"\n" +
	"\x1eCOMMAND_EXECUTION_NOT_ACCEPTED\x10\x00\x12\"\n" +
	"\x1eINVALID_COMMAND_EXECUTION_UUID\x10\x01\x12\"\n" +
	"\x1eCOMMAND_EXECUTION_NOT_FINISHED\x10\x02\x12\x14\n" +
	"\x10INVALID_METADATA\x10\x03\x12\x17\n" +
	"\x13NO_METADATA_ALLOWED\x10\x04\":\n" +
	"\bTimezone\x12\x14\n" +
	"\x05hours\x18\x01 \x01(\x05R\x05hours\x12\x18\n" +
	"\aminutes\x18\x02 \x01(\rR\aminutes\":\n" +
	"\bDuration\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanosBEB\rSiLAFrameworkZ4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_SiLAFramework_proto_rawDescOnce sync.Once
	file_SiLAFramework_proto_rawDescData []byte
)

func file_SiLAFramework_proto_rawDescGZIP() []byte {
	file_SiLAFramework_proto_rawDescOnce.Do(func() {
		file_SiLAFramework_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SiLAFramework_proto_rawDesc), len(file_SiLAFramework_proto_rawDesc)))
	})
	return file_SiLAFramework_proto_rawDescData
}

var file_SiLAFramework_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_SiLAFramework_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_SiLAFramework_proto_goTypes = []any{
	(ExecutionInfo_CommandStatus)(0), // 0: sila2.org.silastandard.ExecutionInfo.CommandStatus
	(FrameworkError_ErrorType)(0),    // 1: sila2.org.silastandard.FrameworkError.ErrorType
	(*String)(nil),                   // 2: sila2.org.silastandard.String
	(*Integer)(nil),                  // 3: sila2.org.silastandard.Integer
	(*Real)(nil),                     // 4: sila2.org.silastandard.Real
	(*Boolean)(nil),                  // 5: sila2.org.silastandard.Boolean
	(*Binary)(nil),                   // 6: sila2.org.silastandard.Binary
	(*Date)(nil),                     // 7: sila2.org.silastandard.Date
	(*Time)(nil),                     // 8: sila2.org.silastandard.Time
	(*Timestamp)(nil),                // 9: sila2.org.silastandard.Timestamp
	(*Any)(nil),                      // 10: sila2.org.silastandard.Any
	(*CommandExecutionUUID)(nil),     // 11: sila2.org.silastandard.CommandExecutionUUID
	(*CommandConfirmation)(nil),      // 12: sila2.org.silastandard.CommandConfirmation
	(*ExecutionInfo)(nil),            // 13: sila2.org.silastandard.ExecutionInfo
	(*SiLAError)(nil),                // 14: sila2.org.silastandard.SiLAError
	(*ValidationError)(nil),          // 15: sila2.org.silastandard.ValidationError
	(*DefinedExecutionError)(nil),    // 16: sila2.org.silastandard.DefinedExecutionError
	(*UndefinedExecutionError)(nil),  // 17: sila2.org.silastandard.UndefinedExecutionError
	(*FrameworkError)(nil),           // 18: sila2.org.silastandard.FrameworkError
	(*Timezone)(nil),                 // 19: sila2.org.silastandard.Timezone
	(*Duration)(nil),                 // 20: sila2.org.silastandard.Duration
}
var file_SiLAFramework_proto_depIdxs = []int32{
	19, // 0: sila2.org.silastandard.Date.timezone:type_name -> sila2.org.silastandard.Timezone
	19, // 1: sila2.org.silastandard.Time.timezone:type_name -> sila2.org.silastandard.Timezone
	19, // 2: sila2.org.silastandard.Timestamp.timezone:type_name -> sila2.org.silastandard.Timezone
	11, // 3: sila2.org.silastandard.CommandConfirmation.commandExecutionUUID:type_name -> sila2.org.silastandard.CommandExecutionUUID
	20, // 4: sila2.org.silastandard.CommandConfirmation.lifetimeOfExecution:type_name -> sila2.org.silastandard.Duration
	0,  // 5: sila2.org.silastandard.ExecutionInfo.commandStatus:type_name -> sila2.org.silastandard.ExecutionInfo.CommandStatus
	4,  // 6: sila2.org.silastandard.ExecutionInfo.progressInfo:type_name -> sila2.org.silastandard.Real
	20, // 7: sila2.org.silastandard.ExecutionInfo.estimatedRemainingTime:type_name -> sila2.org.silastandard.Duration
	20, // 8: sila2.org.silastandard.ExecutionInfo.updatedLifetimeOfExecution:type_name -> sila2.org.silastandard.Duration
	15, // 9: sila2.org.silastandard.SiLAError.validationError:type_name -> sila2.org.silastandard.ValidationError
	16, // 10: sila2.org.silastandard.SiLAError.definedExecutionError:type_name -> sila2.org.silastandard.DefinedExecutionError
	17, // 11: sila2.org.silastandard.SiLAError.undefinedExecutionError:type_name -> sila2.org.silastandard.UndefinedExecutionError
	18, // 12: sila2.org.silastandard.SiLAError.frameworkError:type_name -> sila2.org.silastandard.FrameworkError
	1,  // 13: sila2.org.silastandard.FrameworkError.errorType:type_name -> sila2.org.silastandard.FrameworkError.ErrorType
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_SiLAFramework_proto_init() }
func file_SiLAFramework_proto_init() {
	if File_SiLAFramework_proto != nil {
		return
	}
	file_SiLAFramework_proto_msgTypes[4].OneofWrappers = []any{
		(*Binary_Value)(nil),
		(*Binary_BinaryTransferUUID)(nil),
	}
	file_SiLAFramework_proto_msgTypes[12].OneofWrappers = []any{
		(*SiLAError_ValidationError)(nil),
		(*SiLAError_DefinedExecutionError)(nil),
		(*SiLAError_UndefinedExecutionError)(nil),
		(*SiLAError_FrameworkError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SiLAFramework_proto_rawDesc), len(file_SiLAFramework_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SiLAFramework_proto_goTypes,
		DependencyIndexes: file_SiLAFramework_proto_depIdxs,
		EnumInfos:         file_SiLAFramework_proto_enumTypes,
		MessageInfos:      file_SiLAFramework_proto_msgTypes,
	}.Build()
	File_SiLAFramework_proto = out.File
	file_SiLAFramework_proto_goTypes = nil
	file_SiLAFramework_proto_depIdxs = nil
}
