// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/temperature.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemperatureControllerService_SetTargetTemperature_FullMethodName = "/sila2.temperature.TemperatureControllerService/SetTargetTemperature"
	TemperatureControllerService_GetTemperature_FullMethodName       = "/sila2.temperature.TemperatureControllerService/GetTemperature"
	TemperatureControllerService_SetHeatingState_FullMethodName      = "/sila2.temperature.TemperatureControllerService/SetHeatingState"
)

// TemperatureControllerServiceClient is the client API for TemperatureControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The standard SiLA 2 service for a Temperature Controller (e.g. Column Oven, Detector Heater)
type TemperatureControllerServiceClient interface {
	// Set the target temperature for a specific zone
	SetTargetTemperature(ctx context.Context, in *SetTargetTemperatureRequest, opts ...grpc.CallOption) (*SetTargetTemperatureResponse, error)
	// Get the current actual and target temperatures
	GetTemperature(ctx context.Context, in *GetTemperatureRequest, opts ...grpc.CallOption) (*GetTemperatureResponse, error)
	// Enable or disable heating
	SetHeatingState(ctx context.Context, in *SetHeatingStateRequest, opts ...grpc.CallOption) (*SetHeatingStateResponse, error)
}

type temperatureControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemperatureControllerServiceClient(cc grpc.ClientConnInterface) TemperatureControllerServiceClient {
	return &temperatureControllerServiceClient{cc}
}

func (c *temperatureControllerServiceClient) SetTargetTemperature(ctx context.Context, in *SetTargetTemperatureRequest, opts ...grpc.CallOption) (*SetTargetTemperatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTargetTemperatureResponse)
	err := c.cc.Invoke(ctx, TemperatureControllerService_SetTargetTemperature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temperatureControllerServiceClient) GetTemperature(ctx context.Context, in *GetTemperatureRequest, opts ...grpc.CallOption) (*GetTemperatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemperatureResponse)
	err := c.cc.Invoke(ctx, TemperatureControllerService_GetTemperature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temperatureControllerServiceClient) SetHeatingState(ctx context.Context, in *SetHeatingStateRequest, opts ...grpc.CallOption) (*SetHeatingStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetHeatingStateResponse)
	err := c.cc.Invoke(ctx, TemperatureControllerService_SetHeatingState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemperatureControllerServiceServer is the server API for TemperatureControllerService service.
// All implementations must embed UnimplementedTemperatureControllerServiceServer
// for forward compatibility.
//
// The standard SiLA 2 service for a Temperature Controller (e.g. Column Oven, Detector Heater)
type TemperatureControllerServiceServer interface {
	// Set the target temperature for a specific zone
	SetTargetTemperature(context.Context, *SetTargetTemperatureRequest) (*SetTargetTemperatureResponse, error)
	// Get the current actual and target temperatures
	GetTemperature(context.Context, *GetTemperatureRequest) (*GetTemperatureResponse, error)
	// Enable or disable heating
	SetHeatingState(context.Context, *SetHeatingStateRequest) (*SetHeatingStateResponse, error)
	mustEmbedUnimplementedTemperatureControllerServiceServer()
}

// UnimplementedTemperatureControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemperatureControllerServiceServer struct{}

func (UnimplementedTemperatureControllerServiceServer) SetTargetTemperature(context.Context, *SetTargetTemperatureRequest) (*SetTargetTemperatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTargetTemperature not implemented")
}
func (UnimplementedTemperatureControllerServiceServer) GetTemperature(context.Context, *GetTemperatureRequest) (*GetTemperatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemperature not implemented")
}
func (UnimplementedTemperatureControllerServiceServer) SetHeatingState(context.Context, *SetHeatingStateRequest) (*SetHeatingStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHeatingState not implemented")
}
func (UnimplementedTemperatureControllerServiceServer) mustEmbedUnimplementedTemperatureControllerServiceServer() {
}
func (UnimplementedTemperatureControllerServiceServer) testEmbeddedByValue() {}

// UnsafeTemperatureControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemperatureControllerServiceServer will
// result in compilation errors.
type UnsafeTemperatureControllerServiceServer interface {
	mustEmbedUnimplementedTemperatureControllerServiceServer()
}

func RegisterTemperatureControllerServiceServer(s grpc.ServiceRegistrar, srv TemperatureControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedTemperatureControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemperatureControllerService_ServiceDesc, srv)
}

func _TemperatureControllerService_SetTargetTemperature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTargetTemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureControllerServiceServer).SetTargetTemperature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureControllerService_SetTargetTemperature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureControllerServiceServer).SetTargetTemperature(ctx, req.(*SetTargetTemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemperatureControllerService_GetTemperature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureControllerServiceServer).GetTemperature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureControllerService_GetTemperature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureControllerServiceServer).GetTemperature(ctx, req.(*GetTemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemperatureControllerService_SetHeatingState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHeatingStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureControllerServiceServer).SetHeatingState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemperatureControllerService_SetHeatingState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureControllerServiceServer).SetHeatingState(ctx, req.(*SetHeatingStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemperatureControllerService_ServiceDesc is the grpc.ServiceDesc for TemperatureControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemperatureControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sila2.temperature.TemperatureControllerService",
	HandlerType: (*TemperatureControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTargetTemperature",
			Handler:    _TemperatureControllerService_SetTargetTemperature_Handler,
		},
		{
			MethodName: "GetTemperature",
			Handler:    _TemperatureControllerService_GetTemperature_Handler,
		},
		{
			MethodName: "SetHeatingState",
			Handler:    _TemperatureControllerService_SetHeatingState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/temperature.proto",
}
