// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: temperature.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetTargetTemperatureRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ZoneId             string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	TargetTemperature  float64                `protobuf:"fixed64,2,opt,name=target_temperature,json=targetTemperature,proto3" json:"target_temperature,omitempty"`    // in Celsius
	ProtectTemperature float64                `protobuf:"fixed64,3,opt,name=protect_temperature,json=protectTemperature,proto3" json:"protect_temperature,omitempty"` // safety limit in Celsius
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetTargetTemperatureRequest) Reset() {
	*x = SetTargetTemperatureRequest{}
	mi := &file_temperature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTargetTemperatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTargetTemperatureRequest) ProtoMessage() {}

func (x *SetTargetTemperatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTargetTemperatureRequest.ProtoReflect.Descriptor instead.
func (*SetTargetTemperatureRequest) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{0}
}

func (x *SetTargetTemperatureRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *SetTargetTemperatureRequest) GetTargetTemperature() float64 {
	if x != nil {
		return x.TargetTemperature
	}
	return 0
}

func (x *SetTargetTemperatureRequest) GetProtectTemperature() float64 {
	if x != nil {
		return x.ProtectTemperature
	}
	return 0
}

type SetTargetTemperatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTargetTemperatureResponse) Reset() {
	*x = SetTargetTemperatureResponse{}
	mi := &file_temperature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTargetTemperatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTargetTemperatureResponse) ProtoMessage() {}

func (x *SetTargetTemperatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTargetTemperatureResponse.ProtoReflect.Descriptor instead.
func (*SetTargetTemperatureResponse) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{1}
}

func (x *SetTargetTemperatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTargetTemperatureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTemperatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemperatureRequest) Reset() {
	*x = GetTemperatureRequest{}
	mi := &file_temperature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemperatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemperatureRequest) ProtoMessage() {}

func (x *GetTemperatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemperatureRequest.ProtoReflect.Descriptor instead.
func (*GetTemperatureRequest) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{2}
}

func (x *GetTemperatureRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type GetTemperatureResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActualTemperature  float64                `protobuf:"fixed64,1,opt,name=actual_temperature,json=actualTemperature,proto3" json:"actual_temperature,omitempty"`
	TargetTemperature  float64                `protobuf:"fixed64,2,opt,name=target_temperature,json=targetTemperature,proto3" json:"target_temperature,omitempty"`
	ProtectTemperature float64                `protobuf:"fixed64,3,opt,name=protect_temperature,json=protectTemperature,proto3" json:"protect_temperature,omitempty"`
	HeatingEnabled     bool                   `protobuf:"varint,4,opt,name=heating_enabled,json=heatingEnabled,proto3" json:"heating_enabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTemperatureResponse) Reset() {
	*x = GetTemperatureResponse{}
	mi := &file_temperature_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemperatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemperatureResponse) ProtoMessage() {}

func (x *GetTemperatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemperatureResponse.ProtoReflect.Descriptor instead.
func (*GetTemperatureResponse) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{3}
}

func (x *GetTemperatureResponse) GetActualTemperature() float64 {
	if x != nil {
		return x.ActualTemperature
	}
	return 0
}

func (x *GetTemperatureResponse) GetTargetTemperature() float64 {
	if x != nil {
		return x.TargetTemperature
	}
	return 0
}

func (x *GetTemperatureResponse) GetProtectTemperature() float64 {
	if x != nil {
		return x.ProtectTemperature
	}
	return 0
}

func (x *GetTemperatureResponse) GetHeatingEnabled() bool {
	if x != nil {
		return x.HeatingEnabled
	}
	return false
}

type SetHeatingStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Enable        bool                   `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHeatingStateRequest) Reset() {
	*x = SetHeatingStateRequest{}
	mi := &file_temperature_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHeatingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHeatingStateRequest) ProtoMessage() {}

func (x *SetHeatingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHeatingStateRequest.ProtoReflect.Descriptor instead.
func (*SetHeatingStateRequest) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{4}
}

func (x *SetHeatingStateRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *SetHeatingStateRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type SetHeatingStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHeatingStateResponse) Reset() {
	*x = SetHeatingStateResponse{}
	mi := &file_temperature_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHeatingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHeatingStateResponse) ProtoMessage() {}

func (x *SetHeatingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHeatingStateResponse.ProtoReflect.Descriptor instead.
func (*SetHeatingStateResponse) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{5}
}

func (x *SetHeatingStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetHeatingStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_temperature_proto protoreflect.FileDescriptor

const file_temperature_proto_rawDesc = "" +
	"\n" +
	"\x11temperature.proto\x12;sila2.org.silastandard.core.temperaturecontrollerservice.v1\"\x96\x01\n" +
	"\x1bSetTargetTemperatureRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12-\n" +
	"\x12target_temperature\x18\x02 \x01(\x01R\x11targetTemperature\x12/\n" +
	"\x13protect_temperature\x18\x03 \x01(\x01R\x12protectTemperature\"R\n" +
	"\x1cSetTargetTemperatureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x15GetTemperatureRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\"\xd0\x01\n" +
	"\x16GetTemperatureResponse\x12-\n" +
	"\x12actual_temperature\x18\x01 \x01(\x01R\x11actualTemperature\x12-\n" +
	"\x12target_temperature\x18\x02 \x01(\x01R\x11targetTemperature\x12/\n" +
	"\x13protect_temperature\x18\x03 \x01(\x01R\x12protectTemperature\x12'\n" +
	"\x0fheating_enabled\x18\x04 \x01(\bR\x0eheatingEnabled\"I\n" +
	"\x16SetHeatingStateRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x16\n" +
	"\x06enable\x18\x02 \x01(\bR\x06enable\"M\n" +
	"\x17SetHeatingStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xed\x04\n" +
	"\x1cTemperatureControllerService\x12\xcd\x01\n" +
	"\x14SetTargetTemperature\x12X.sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetTargetTemperatureRequest\x1aY.sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetTargetTemperatureResponse\"\x00\x12\xbb\x01\n" +
	"\x0eGetTemperature\x12R.sila2.org.silastandard.core.temperaturecontrollerservice.v1.GetTemperatureRequest\x1aS.sila2.org.silastandard.core.temperaturecontrollerservice.v1.GetTemperatureResponse\"\x00\x12\xbe\x01\n" +
	"\x0fSetHeatingState\x12S.sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetHeatingStateRequest\x1aT.sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetHeatingStateResponse\"\x00B6Z4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_temperature_proto_rawDescOnce sync.Once
	file_temperature_proto_rawDescData []byte
)

func file_temperature_proto_rawDescGZIP() []byte {
	file_temperature_proto_rawDescOnce.Do(func() {
		file_temperature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temperature_proto_rawDesc), len(file_temperature_proto_rawDesc)))
	})
	return file_temperature_proto_rawDescData
}

var file_temperature_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_temperature_proto_goTypes = []any{
	(*SetTargetTemperatureRequest)(nil),  // 0: sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetTargetTemperatureRequest
	(*SetTargetTemperatureResponse)(nil), // 1: sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetTargetTemperatureResponse
	(*GetTemperatureRequest)(nil),        // 2: sila2.org.silastandard.core.temperaturecontrollerservice.v1.GetTemperatureRequest
	(*GetTemperatureResponse)(nil),       // 3: sila2.org.silastandard.core.temperaturecontrollerservice.v1.GetTemperatureResponse
	(*SetHeatingStateRequest)(nil),       // 4: sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetHeatingStateRequest
	(*SetHeatingStateResponse)(nil),      // 5: sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetHeatingStateResponse
}
var file_temperature_proto_depIdxs = []int32{
	0, // 0: sila2.org.silastandard.core.temperaturecontrollerservice.v1.TemperatureControllerService.SetTargetTemperature:input_type -> sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetTargetTemperatureRequest
	2, // 1: sila2.org.silastandard.core.temperaturecontrollerservice.v1.TemperatureControllerService.GetTemperature:input_type -> sila2.org.silastandard.core.temperaturecontrollerservice.v1.GetTemperatureRequest
	4, // 2: sila2.org.silastandard.core.temperaturecontrollerservice.v1.TemperatureControllerService.SetHeatingState:input_type -> sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetHeatingStateRequest
	1, // 3: sila2.org.silastandard.core.temperaturecontrollerservice.v1.TemperatureControllerService.SetTargetTemperature:output_type -> sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetTargetTemperatureResponse
	3, // 4: sila2.org.silastandard.core.temperaturecontrollerservice.v1.TemperatureControllerService.GetTemperature:output_type -> sila2.org.silastandard.core.temperaturecontrollerservice.v1.GetTemperatureResponse
	5, // 5: sila2.org.silastandard.core.temperaturecontrollerservice.v1.TemperatureControllerService.SetHeatingState:output_type -> sila2.org.silastandard.core.temperaturecontrollerservice.v1.SetHeatingStateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temperature_proto_init() }
func file_temperature_proto_init() {
	if File_temperature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temperature_proto_rawDesc), len(file_temperature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_temperature_proto_goTypes,
		DependencyIndexes: file_temperature_proto_depIdxs,
		MessageInfos:      file_temperature_proto_msgTypes,
	}.Build()
	File_temperature_proto = out.File
	file_temperature_proto_goTypes = nil
	file_temperature_proto_depIdxs = nil
}
