// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/valve.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwitchValveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValveId       string                 `protobuf:"bytes,1,opt,name=valve_id,json=valveId,proto3" json:"valve_id,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"` // e.g. 0 (Off/Load) or 1 (On/Inject)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchValveRequest) Reset() {
	*x = SwitchValveRequest{}
	mi := &file_proto_valve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchValveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchValveRequest) ProtoMessage() {}

func (x *SwitchValveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchValveRequest.ProtoReflect.Descriptor instead.
func (*SwitchValveRequest) Descriptor() ([]byte, []int) {
	return file_proto_valve_proto_rawDescGZIP(), []int{0}
}

func (x *SwitchValveRequest) GetValveId() string {
	if x != nil {
		return x.ValveId
	}
	return ""
}

func (x *SwitchValveRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type SwitchValveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchValveResponse) Reset() {
	*x = SwitchValveResponse{}
	mi := &file_proto_valve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchValveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchValveResponse) ProtoMessage() {}

func (x *SwitchValveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchValveResponse.ProtoReflect.Descriptor instead.
func (*SwitchValveResponse) Descriptor() ([]byte, []int) {
	return file_proto_valve_proto_rawDescGZIP(), []int{1}
}

func (x *SwitchValveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwitchValveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetValveStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValveId       string                 `protobuf:"bytes,1,opt,name=valve_id,json=valveId,proto3" json:"valve_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValveStateRequest) Reset() {
	*x = GetValveStateRequest{}
	mi := &file_proto_valve_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValveStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValveStateRequest) ProtoMessage() {}

func (x *GetValveStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valve_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValveStateRequest.ProtoReflect.Descriptor instead.
func (*GetValveStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_valve_proto_rawDescGZIP(), []int{2}
}

func (x *GetValveStateRequest) GetValveId() string {
	if x != nil {
		return x.ValveId
	}
	return ""
}

type GetValveStateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPosition int32                  `protobuf:"varint,1,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetValveStateResponse) Reset() {
	*x = GetValveStateResponse{}
	mi := &file_proto_valve_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValveStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValveStateResponse) ProtoMessage() {}

func (x *GetValveStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valve_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValveStateResponse.ProtoReflect.Descriptor instead.
func (*GetValveStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_valve_proto_rawDescGZIP(), []int{3}
}

func (x *GetValveStateResponse) GetCurrentPosition() int32 {
	if x != nil {
		return x.CurrentPosition
	}
	return 0
}

var File_proto_valve_proto protoreflect.FileDescriptor

const file_proto_valve_proto_rawDesc = "" +
	"\n" +
	"\x11proto/valve.proto\x12\vsila2.valve\"K\n" +
	"\x12SwitchValveRequest\x12\x19\n" +
	"\bvalve_id\x18\x01 \x01(\tR\avalveId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\"I\n" +
	"\x13SwitchValveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x14GetValveStateRequest\x12\x19\n" +
	"\bvalve_id\x18\x01 \x01(\tR\avalveId\"B\n" +
	"\x15GetValveStateResponse\x12)\n" +
	"\x10current_position\x18\x01 \x01(\x05R\x0fcurrentPosition2\xc6\x01\n" +
	"\x16ValveControllerService\x12R\n" +
	"\vSwitchValve\x12\x1f.sila2.valve.SwitchValveRequest\x1a .sila2.valve.SwitchValveResponse\"\x00\x12X\n" +
	"\rGetValveState\x12!.sila2.valve.GetValveStateRequest\x1a\".sila2.valve.GetValveStateResponse\"\x00B6Z4chromatography-workstation/edge/internal/sila2/pb;pbb\x06proto3"

var (
	file_proto_valve_proto_rawDescOnce sync.Once
	file_proto_valve_proto_rawDescData []byte
)

func file_proto_valve_proto_rawDescGZIP() []byte {
	file_proto_valve_proto_rawDescOnce.Do(func() {
		file_proto_valve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_valve_proto_rawDesc), len(file_proto_valve_proto_rawDesc)))
	})
	return file_proto_valve_proto_rawDescData
}

var file_proto_valve_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_valve_proto_goTypes = []any{
	(*SwitchValveRequest)(nil),    // 0: sila2.valve.SwitchValveRequest
	(*SwitchValveResponse)(nil),   // 1: sila2.valve.SwitchValveResponse
	(*GetValveStateRequest)(nil),  // 2: sila2.valve.GetValveStateRequest
	(*GetValveStateResponse)(nil), // 3: sila2.valve.GetValveStateResponse
}
var file_proto_valve_proto_depIdxs = []int32{
	0, // 0: sila2.valve.ValveControllerService.SwitchValve:input_type -> sila2.valve.SwitchValveRequest
	2, // 1: sila2.valve.ValveControllerService.GetValveState:input_type -> sila2.valve.GetValveStateRequest
	1, // 2: sila2.valve.ValveControllerService.SwitchValve:output_type -> sila2.valve.SwitchValveResponse
	3, // 3: sila2.valve.ValveControllerService.GetValveState:output_type -> sila2.valve.GetValveStateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_valve_proto_init() }
func file_proto_valve_proto_init() {
	if File_proto_valve_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_valve_proto_rawDesc), len(file_proto_valve_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_valve_proto_goTypes,
		DependencyIndexes: file_proto_valve_proto_depIdxs,
		MessageInfos:      file_proto_valve_proto_msgTypes,
	}.Build()
	File_proto_valve_proto = out.File
	file_proto_valve_proto_goTypes = nil
	file_proto_valve_proto_depIdxs = nil
}
