// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/valve.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValveControllerService_SwitchValve_FullMethodName   = "/sila2.valve.ValveControllerService/SwitchValve"
	ValveControllerService_GetValveState_FullMethodName = "/sila2.valve.ValveControllerService/GetValveState"
)

// ValveControllerServiceClient is the client API for ValveControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The standard SiLA 2 service for Valve Control (Events/Valves)
type ValveControllerServiceClient interface {
	// Switch a specific valve to a given position
	SwitchValve(ctx context.Context, in *SwitchValveRequest, opts ...grpc.CallOption) (*SwitchValveResponse, error)
	// Get the current position/state of a valve
	GetValveState(ctx context.Context, in *GetValveStateRequest, opts ...grpc.CallOption) (*GetValveStateResponse, error)
}

type valveControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValveControllerServiceClient(cc grpc.ClientConnInterface) ValveControllerServiceClient {
	return &valveControllerServiceClient{cc}
}

func (c *valveControllerServiceClient) SwitchValve(ctx context.Context, in *SwitchValveRequest, opts ...grpc.CallOption) (*SwitchValveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchValveResponse)
	err := c.cc.Invoke(ctx, ValveControllerService_SwitchValve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valveControllerServiceClient) GetValveState(ctx context.Context, in *GetValveStateRequest, opts ...grpc.CallOption) (*GetValveStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValveStateResponse)
	err := c.cc.Invoke(ctx, ValveControllerService_GetValveState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValveControllerServiceServer is the server API for ValveControllerService service.
// All implementations must embed UnimplementedValveControllerServiceServer
// for forward compatibility.
//
// The standard SiLA 2 service for Valve Control (Events/Valves)
type ValveControllerServiceServer interface {
	// Switch a specific valve to a given position
	SwitchValve(context.Context, *SwitchValveRequest) (*SwitchValveResponse, error)
	// Get the current position/state of a valve
	GetValveState(context.Context, *GetValveStateRequest) (*GetValveStateResponse, error)
	mustEmbedUnimplementedValveControllerServiceServer()
}

// UnimplementedValveControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValveControllerServiceServer struct{}

func (UnimplementedValveControllerServiceServer) SwitchValve(context.Context, *SwitchValveRequest) (*SwitchValveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchValve not implemented")
}
func (UnimplementedValveControllerServiceServer) GetValveState(context.Context, *GetValveStateRequest) (*GetValveStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValveState not implemented")
}
func (UnimplementedValveControllerServiceServer) mustEmbedUnimplementedValveControllerServiceServer() {
}
func (UnimplementedValveControllerServiceServer) testEmbeddedByValue() {}

// UnsafeValveControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValveControllerServiceServer will
// result in compilation errors.
type UnsafeValveControllerServiceServer interface {
	mustEmbedUnimplementedValveControllerServiceServer()
}

func RegisterValveControllerServiceServer(s grpc.ServiceRegistrar, srv ValveControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedValveControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValveControllerService_ServiceDesc, srv)
}

func _ValveControllerService_SwitchValve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchValveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValveControllerServiceServer).SwitchValve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValveControllerService_SwitchValve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValveControllerServiceServer).SwitchValve(ctx, req.(*SwitchValveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValveControllerService_GetValveState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValveStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValveControllerServiceServer).GetValveState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValveControllerService_GetValveState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValveControllerServiceServer).GetValveState(ctx, req.(*GetValveStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValveControllerService_ServiceDesc is the grpc.ServiceDesc for ValveControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValveControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sila2.valve.ValveControllerService",
	HandlerType: (*ValveControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwitchValve",
			Handler:    _ValveControllerService_SwitchValve_Handler,
		},
		{
			MethodName: "GetValveState",
			Handler:    _ValveControllerService_GetValveState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/valve.proto",
}
