using DevExpress.XtraEditors.Controls;

namespace IBrainChrom2018.Report;

public class XtraEditors_CN : Localizer
{
	public override string Language => "简体中文";

	public override string GetLocalizedString(StringId id)
	{
		return id switch
		{
			StringId.TextEditMenuCopy => "复制(&C)", 
			StringId.TextEditMenuCut => "剪切(&T)", 
			StringId.TextEditMenuDelete => "删除(&D)", 
			StringId.TextEditMenuPaste => "粘贴(&P)", 
			StringId.TextEditMenuSelectAll => "全选(&A)", 
			StringId.TextEditMenuUndo => "撤消(&U)", 
			StringId.UnknownPictureFormat => "未知图片格式", 
			StringId.DateEditToday => "今天", 
			StringId.DateEditClear => "清空", 
			StringId.DataEmpty => "无图像", 
			StringId.ColorTabWeb => "网页", 
			StringId.ColorTabSystem => "系统", 
			StringId.ColorTabCustom => "自定义", 
			StringId.CheckUnchecked => "未选择", 
			StringId.CheckIndeterminate => "不确定", 
			StringId.CheckChecked => "已选择", 
			StringId.CaptionError => "标题错误", 
			StringId.Cancel => "取消", 
			StringId.CalcError => "计算错误", 
			StringId.CalcButtonBack => base.GetLocalizedString(id), 
			StringId.CalcButtonC => base.GetLocalizedString(id), 
			StringId.CalcButtonCE => base.GetLocalizedString(id), 
			StringId.CalcButtonMC => base.GetLocalizedString(id), 
			StringId.CalcButtonMR => base.GetLocalizedString(id), 
			StringId.CalcButtonMS => base.GetLocalizedString(id), 
			StringId.CalcButtonMx => base.GetLocalizedString(id), 
			StringId.CalcButtonSqrt => base.GetLocalizedString(id), 
			StringId.OK => "确定", 
			StringId.PictureEditMenuCopy => "复制(&C)", 
			StringId.PictureEditMenuCut => "剪切(&T)", 
			StringId.PictureEditMenuDelete => "删除(&D)", 
			StringId.PictureEditMenuLoad => "加载(&L)", 
			StringId.PictureEditMenuPaste => "粘贴(&P)", 
			StringId.PictureEditMenuSave => "保存(&S)", 
			StringId.PictureEditOpenFileError => "错误图片格式", 
			StringId.PictureEditOpenFileErrorCaption => "打开错误", 
			StringId.PictureEditOpenFileFilter => "位 图文件(*.bmp)|*.bmp|GIF动画 (*.gif)|*.gif|JPEG(*.jpg;*.jpeg)|*.jpg;*.jpeg|ICO(*.ico)|*.ico|所有图片文 件|*.bmp;*.gif;*.jpeg;*.jpg;*.ico|所有文件(*.*)|*.*", 
			StringId.PictureEditOpenFileTitle => "打开", 
			StringId.PictureEditSaveFileFilter => "位图文件(*.bmp)|*.bmp|GIF动画(*.gif)|*.gif|JPEG(*.jpg)|*.jpg", 
			StringId.PictureEditSaveFileTitle => "保存为", 
			StringId.TabHeaderButtonClose => "关闭", 
			StringId.TabHeaderButtonNext => "下一页", 
			StringId.TabHeaderButtonPrev => "上一页", 
			StringId.XtraMessageBoxAbortButtonText => "中断(&A)", 
			StringId.XtraMessageBoxCancelButtonText => "取消(&C)", 
			StringId.XtraMessageBoxIgnoreButtonText => "忽略(&I)", 
			StringId.XtraMessageBoxNoButtonText => "否(&N)", 
			StringId.XtraMessageBoxOkButtonText => "确定(&O)", 
			StringId.XtraMessageBoxRetryButtonText => "重试(&R)", 
			StringId.XtraMessageBoxYesButtonText => "是(&Y)", 
			StringId.ImagePopupEmpty => "(空)", 
			StringId.ImagePopupPicture => "(图片)", 
			StringId.InvalidValueText => "无效的值", 
			StringId.LookUpEditValueIsNull => "[无数据]", 
			StringId.LookUpInvalidEditValueType => "无效的数据类型", 
			StringId.MaskBoxValidateError => "输入数值不完整. 是否须要修改? 是 - 回到编辑模式以修改数值. 否 - 保持原来数值. 取消 - 回复原来数值. ", 
			StringId.NavigatorAppendButtonHint => "添加", 
			StringId.NavigatorCancelEditButtonHint => "取消编辑", 
			StringId.NavigatorEditButtonHint => "编辑", 
			StringId.NavigatorEndEditButtonHint => "结束编辑", 
			StringId.NavigatorFirstButtonHint => "第一条", 
			StringId.NavigatorLastButtonHint => "最后一条", 
			StringId.NavigatorNextButtonHint => "下一条", 
			StringId.NavigatorNextPageButtonHint => "下一页", 
			StringId.NavigatorPreviousButtonHint => "上一条", 
			StringId.NavigatorPreviousPageButtonHint => "上一页", 
			StringId.NavigatorRemoveButtonHint => "删除", 
			StringId.NavigatorTextStringFormat => "记录{0}/{1}", 
			StringId.None => "", 
			StringId.NotValidArrayLength => "无效的数组长度.", 
			_ => base.GetLocalizedString(id), 
		};
	}
}
