using DevExpress.XtraReports.Localization;

namespace IBrainChrom2018.Report;

public class XtraReports_CN : ReportLocalizer
{
	public override string Language => "简体中文";

	public override string GetLocalizedString(ReportStringId id)
	{
		return id switch
		{
			ReportStringId.BandDsg_QuantityPerPage => "一个页面集合", 
			ReportStringId.BandDsg_QuantityPerReport => "一个报表集合", 
			ReportStringId.BCForm_Lbl_Binding => "结合", 
			ReportStringId.BCForm_Lbl_Property => "属性", 
			ReportStringId.CatAppearance => "版面", 
			ReportStringId.CatBehavior => "状态", 
			ReportStringId.CatData => "数据", 
			ReportStringId.CatLayout => "布局", 
			ReportStringId.CatNavigation => "导航", 
			ReportStringId.CatPageSettings => "页面设置", 
			ReportStringId.Cmd_AlignToGrid => "对齐网格线", 
			ReportStringId.Cmd_BottomMargin => "底端边缘", 
			ReportStringId.Cmd_BringToFront => "移到最上层", 
			ReportStringId.Cmd_Copy => "复制", 
			ReportStringId.Cmd_Cut => "剪贴", 
			ReportStringId.Cmd_Delete => "删除", 
			ReportStringId.Cmd_Detail => "详细", 
			ReportStringId.Cmd_DetailReport => "详细报表", 
			ReportStringId.Cmd_GroupFooter => "群组尾", 
			ReportStringId.Cmd_GroupHeader => "群组首", 
			ReportStringId.Cmd_InsertBand => "插入区段", 
			ReportStringId.Cmd_InsertDetailReport => "插入详细报表", 
			ReportStringId.Cmd_InsertUnboundDetailReport => "非绑定", 
			ReportStringId.Cmd_PageFooter => "页尾", 
			ReportStringId.Cmd_PageHeader => "页首", 
			ReportStringId.Cmd_Paste => "粘贴", 
			ReportStringId.Cmd_Properties => "属性", 
			ReportStringId.Cmd_ReportFooter => "报表尾", 
			ReportStringId.Cmd_ReportHeader => "报表首", 
			ReportStringId.Cmd_RtfClear => "清除", 
			ReportStringId.Cmd_RtfLoad => "加载文件...", 
			ReportStringId.Cmd_SendToBack => "移到最下层", 
			ReportStringId.Cmd_TableDelete => "删除(&L)", 
			ReportStringId.Cmd_TableDeleteCell => "单元格(&L)", 
			ReportStringId.Cmd_TableDeleteColumn => "列(&C)", 
			ReportStringId.Cmd_TableDeleteRow => "行(&R)", 
			ReportStringId.Cmd_TableInsert => "插入(&I)", 
			ReportStringId.Cmd_TableInsertCell => "单元格(&C)", 
			ReportStringId.Cmd_TableInsertColumnToLeft => "左列(&L)", 
			ReportStringId.Cmd_TableInsertColumnToRight => "右列(&R)", 
			ReportStringId.Cmd_TableInsertRowAbove => "上行(&A)", 
			ReportStringId.Cmd_TableInsertRowBelow => "下行(&B)", 
			ReportStringId.Cmd_TopMargin => "顶端边缘", 
			ReportStringId.Cmd_ViewCode => "检视代码", 
			ReportStringId.FindForm_Msg_FinishedSearching => "搜索文件完成", 
			ReportStringId.FindForm_Msg_TotalFound => "合计查找:", 
			ReportStringId.Msg_CantFitBarcodeToControlBounds => "条形码控件的边界太小", 
			ReportStringId.Msg_CreateReportInstance => "您试图打开一个不同类型的报表来编辑。是否确定建立实例？", 
			ReportStringId.Msg_CreateSomeInstance => "在窗体中不能建立两个实例类。", 
			ReportStringId.Msg_CyclicBoormarks => "报表循环书签", 
			ReportStringId.Msg_DontSupportMulticolumn => "详细报表不支持多字段。", 
			ReportStringId.Msg_FileCorrupted => "不能加载报表，文件可能被破坏或者报表组件丢失。", 
			ReportStringId.Msg_FileNotFound => "文件没有找到", 
			ReportStringId.Msg_FillDataError => "数据加载时发生错误。错误为：", 
			ReportStringId.Msg_IncorrectArgument => "参数值输入不正确", 
			ReportStringId.Msg_IncorrectBandType => "无效的带型", 
			ReportStringId.Msg_InvalidBarcodeText => "在文本中有无效的字符", 
			ReportStringId.Msg_InvalidBarcodeTextFormat => "无效的文本格式", 
			ReportStringId.Msg_InvalidMethodCall => "对象的当前状态下不能调用此方法", 
			ReportStringId.Msg_InvalidReportSource => "无法设置原报表", 
			ReportStringId.Msg_InvPropName => "无效的属性名", 
			ReportStringId.Msg_ScriptError => "在脚本中发现错误： {0}", 
			ReportStringId.Msg_ScriptExecutionError => "在脚本执行过程中发现错误 {0}:  {1} 过程 {0} 被运行，将不能再被调用。", 
			ReportStringId.Msg_WrongReportClassName => "一个错误发生在并行化期间 - 可能是报表类名错误", 
			ReportStringId.MultiColumnDesignMsg1 => "重复列之间的空位", 
			ReportStringId.MultiColumnDesignMsg2 => "控件位置不正确，将会导致打印错误", 
			ReportStringId.PanelDesignMsg => "在此可放置不同控件", 
			ReportStringId.RepTabCtl_Designer => "设计", 
			ReportStringId.RepTabCtl_HtmlView => "HTML视图", 
			ReportStringId.RepTabCtl_Preview => "预览", 
			ReportStringId.SSForm_Btn_Close => "关闭", 
			ReportStringId.SSForm_Caption => "式样单编辑", 
			ReportStringId.SSForm_Msg_FileFilter => "Report StyleSheet files (*.repss)|*.repss|All files (*.*)|*.*", 
			ReportStringId.SSForm_Msg_InvalidFileFormat => "无效的文件格式", 
			ReportStringId.SSForm_Msg_MoreThanOneStyle => "你选择了多过一个以上的式样", 
			ReportStringId.SSForm_Msg_NoStyleSelected => "没有式样被选中", 
			ReportStringId.SSForm_Msg_SelectedStylesText => "被选中的式样...", 
			ReportStringId.SSForm_Msg_StyleNamePreviewPostfix => "式样", 
			ReportStringId.SSForm_Msg_StyleSheetError => "StyleSheet错误", 
			ReportStringId.SSForm_TTip_AddStyle => "添加式样", 
			ReportStringId.SSForm_TTip_ClearStyles => "清除式样", 
			ReportStringId.SSForm_TTip_LoadStyles => "从文件中读入式样", 
			ReportStringId.SSForm_TTip_PurgeStyles => "清除式样", 
			ReportStringId.SSForm_TTip_RemoveStyle => "移除式样", 
			ReportStringId.SSForm_TTip_SaveStyles => "保存式样到文件", 
			ReportStringId.UD_FormCaption => "XtraReport设计", 
			ReportStringId.UD_Msg_ReportChanged => "报表内容已被修改，是否须要储存？", 
			ReportStringId.UD_ReportDesigner => "XtraReport设计", 
			ReportStringId.UD_TTip_AlignBottom => "对齐主控项的下缘", 
			ReportStringId.UD_TTip_AlignHorizontalCenters => "对齐主控项的垂直中间", 
			ReportStringId.UD_TTip_AlignLeft => "对齐主控项的左缘", 
			ReportStringId.UD_TTip_AlignRight => "对齐主控项的右缘", 
			ReportStringId.UD_TTip_AlignToGrid => "对齐网格线", 
			ReportStringId.UD_TTip_AlignTop => "对齐主控项的上缘", 
			ReportStringId.UD_TTip_AlignVerticalCenters => "对齐主控项的水平中央", 
			ReportStringId.UD_TTip_BringToFront => "移到最上层", 
			ReportStringId.UD_TTip_CenterHorizontally => "水平置中", 
			ReportStringId.UD_TTip_CenterVertically => "垂直置中", 
			ReportStringId.UD_TTip_EditCopy => "复制", 
			ReportStringId.UD_TTip_EditCut => "剪贴", 
			ReportStringId.UD_TTip_EditPaste => "粘贴", 
			ReportStringId.UD_TTip_FileOpen => "打开文件", 
			ReportStringId.UD_TTip_FileSave => "保存文件", 
			ReportStringId.UD_TTip_FormatAlignLeft => "左对齐", 
			ReportStringId.UD_TTip_FormatAlignRight => "右对齐", 
			ReportStringId.UD_TTip_FormatBackColor => "背景颜色", 
			ReportStringId.UD_TTip_FormatBold => "粗体", 
			ReportStringId.UD_TTip_FormatCenter => "居中", 
			ReportStringId.UD_TTip_FormatFontName => "字体", 
			ReportStringId.UD_TTip_FormatFontSize => "大小", 
			ReportStringId.UD_TTip_FormatForeColor => "前景颜色", 
			ReportStringId.UD_TTip_FormatItalic => "斜体", 
			ReportStringId.UD_TTip_FormatJustify => "两端对齐", 
			ReportStringId.UD_TTip_FormatUnderline => "下划线", 
			ReportStringId.UD_TTip_HorizSpaceConcatenate => "移除水平间距", 
			ReportStringId.UD_TTip_HorizSpaceDecrease => "减少水平间距", 
			ReportStringId.UD_TTip_HorizSpaceIncrease => "增加水平间距", 
			ReportStringId.UD_TTip_HorizSpaceMakeEqual => "将垂直间距设为相等", 
			ReportStringId.UD_TTip_Redo => "恢复", 
			ReportStringId.UD_TTip_SendToBack => "移到最下层", 
			ReportStringId.UD_TTip_SizeToControl => "设置成相同大小", 
			ReportStringId.UD_TTip_SizeToControlHeight => "设置成相同高度", 
			ReportStringId.UD_TTip_SizeToControlWidth => "设置成相同宽度", 
			ReportStringId.UD_TTip_SizeToGrid => "依网格线调整大小", 
			ReportStringId.UD_TTip_Undo => "撤消", 
			ReportStringId.UD_TTip_VertSpaceConcatenate => "移除垂直间距", 
			ReportStringId.UD_TTip_VertSpaceDecrease => "减少垂直间距", 
			ReportStringId.UD_TTip_VertSpaceIncrease => "增加垂直间距", 
			ReportStringId.UD_TTip_VertSpaceMakeEqual => "将垂直间距设为相等", 
			_ => base.GetLocalizedString(id), 
		};
	}
}
